# Pipeline Scraping Paper Dosen Infokom UNESA
**Modular Pipeline** | All logic in `scraping_modules/` | Notebook = orchestrator only.

| Step | Function | Output |
|------|----------|--------|
| 1 | `run_scopus_scraping()` | `dosen_papers_scopus.csv` (Scopus Export via Selenium) |
| 2 | `run_scopus_processing()` | `dosen_papers_scopus.csv` (Clean + Dedup + TLDR) |
| 3 | `run_supabase_insert()` | Supabase DB (Upsert + Link Papers to Lecturers) |
| 4 | `run_scholar_scraping()` | `dosen_papers_scholar_raw.csv` (Google Scholar via SerpAPI) |
| 5 | `run_scholar_enrichment()` | `dosen_papers_scholar.csv` (Keywords, Abstract, DOI, TLDR) |

> **Prerequisite:** Run `scraping_dosen_infokom_v4.ipynb` first to generate `dosen_infokom_final.csv`.
> Ensure `credentials_new.json` is present in the root folder.

In [2]:
# Setup & Imports
import sys, importlib
from pathlib import Path

ROOT_DIR = Path.cwd()
if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))

# Force reload modules to pick up latest changes
for mod_name in list(sys.modules.keys()):
    if 'scraping_modules' in mod_name:
        del sys.modules[mod_name]

from scraping_modules import paper_pipeline, config
print(f"Save Directory: {config.SAVE_DIR}")
print(f"SerpAPI: {'Active' if config.SERPAPI_KEY else 'Inactive'}")
print(f"BrightData Proxy: {'Active' if config.BD_USER_SERP else 'Inactive'}")
print(f"Scopus Login: {'Active' if config.SCIVAL_EMAIL else 'Inactive'}")

✅ Config: Loaded Dual-Proxy Credentials (Unlocker + SERP)
✅ Config: Loaded Credentials (Supabase: https://wfjzdhaaldwyiajbyzln.supabase.co)
Save Directory: C:\Users\rizky_11yf1be\Desktop\Tugas_Akhir\notebooks\scraping\file_tabulars
SerpAPI: Active
BrightData Proxy: Active
Scopus Login: Active

---
### Step 1: Scopus Scraping (Selenium Export)
Scrape papers from Scopus for all lecturers with `scopus_id`.
Uses Selenium to automate Scopus plain-text export downloads.

In [2]:
paper_pipeline.run_scopus_scraping()

📚 STEP 1: SCOPUS SCRAPING
==================================================
   🎯 Found 103 Scopus IDs to scrape.
📍 Logging in...
✅ Login Successful
   [1/103] Processing ID: 57215981815 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 14 papers.
   [2/103] Processing ID: 57201351214 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 21 papers.
   [3/103] Processing ID: 57193733535 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 37 papers.
   [4/103] Processing ID: 57201350852 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 7 papers.
   [5/103] Processing ID: 56038565900 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 21 papers.
   [6/103] Processing ID: 57189691714 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 20 papers.
   [7/103] Processing ID: 57195258934 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 28 papers.
   [8/103] Processing ID: 57202388830 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 9 papers.
   [9/103] Processing ID: 57193503081 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 8 papers.
   [10/103] Processing ID: 57208593104 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 12 papers.
   [11/103] Processing ID: 58175681300 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 8 papers.
   [12/103] Processing ID: 57832548400 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 10 papers.
   [13/103] Processing ID: 57883297200 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 1 papers.
   [14/103] Processing ID: 57211891237 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 19 papers.
   [15/103] Processing ID: 57523626600 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 3 papers.
   [16/103] Processing ID: 57728659500 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 5 papers.
   [17/103] Processing ID: 57200535816 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 4 papers.
   [18/103] Processing ID: 57852965300 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 9 papers.
   [19/103] Processing ID: 57214681538 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 6 papers.
   [20/103] Processing ID: 58306956800 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 5 papers.
   [21/103] Processing ID: 58922897800 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 11 papers.
   [22/103] Processing ID: 57195553791 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 33 papers.
   [23/103] Processing ID: 57216963152 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 19 papers.
   [24/103] Processing ID: 53263227700 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 43 papers.
   [25/103] Processing ID: 58695425300 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 4 papers.
   [26/103] Processing ID: 57216299222 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 49 papers.
   [27/103] Processing ID: 57200571569 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 4 papers.
   [28/103] Processing ID: 60116134800 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 1 papers.
   [29/103] Processing ID: 59034929100 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 2 papers.
   [30/103] Processing ID: 59334460400 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 3 papers.
   [31/103] Processing ID: 59934305100 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 4 papers.
   [32/103] Processing ID: 57222610545 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 4 papers.
   [33/103] Processing ID: 59245618200 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 5 papers.
   [34/103] Processing ID: 59144107400 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 5 papers.
   [35/103] Processing ID: 60116248000 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 1 papers.
   [36/103] Processing ID: 8215287000 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 29 papers.
   [37/103] Processing ID: 58779049200 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 1 papers.
   [38/103] Processing ID: 57201351339 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 9 papers.
   [39/103] Processing ID: 57201862664 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 8 papers.
   [40/103] Processing ID: 57192095275 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 25 papers.
   [41/103] Processing ID: 55648855000 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 56 papers.
   [42/103] Processing ID: 57200562830 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 28 papers.
   [43/103] Processing ID: 57190439932 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 52 papers.
   [44/103] Processing ID: 59236235200 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 1 papers.
   [45/103] Processing ID: 56516857300 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 46 papers.
   [46/103] Processing ID: 57203283361 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 18 papers.
   [47/103] Processing ID: 57202236759 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 19 papers.
   [48/103] Processing ID: 57217603667 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 9 papers.
   [49/103] Processing ID: 57201850396 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 10 papers.
   [50/103] Processing ID: 57191815729 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 73 papers.
   [51/103] Processing ID: 57201862550 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 19 papers.
   [52/103] Processing ID: 57219896785 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 1 papers.
   [53/103] Processing ID: 57201858423 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 16 papers.
   [54/103] Processing ID: 57220057023 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 13 papers.
   [55/103] Processing ID: 57209417564 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 12 papers.
   [56/103] Processing ID: 57201196206 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 2 papers.
   [57/103] Processing ID: 57216862548 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 71 papers.
   [58/103] Processing ID: 57201853815 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 19 papers.
   [59/103] Processing ID: 60344435300 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 2 papers.
   [60/103] Processing ID: 57252571000 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 8 papers.
   [61/103] Processing ID: 57189248053 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 4 papers.
   [62/103] Processing ID: 56205430400 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 20 papers.
   [63/103] Processing ID: 54973804500 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 39 papers.
   [64/103] Processing ID: 57215307484 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 14 papers.
   [65/103] Processing ID: 57221750827 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 5 papers.
   [66/103] Processing ID: 57204996170 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 12 papers.
   [67/103] Processing ID: 57209460473 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 6 papers.
   [68/103] Processing ID: 57053275600 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 20 papers.
   [69/103] Processing ID: 57510103300 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 20 papers.
   [70/103] Processing ID: 57204880644 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 4 papers.
   [71/103] Processing ID: 57221534129 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 6 papers.
   [72/103] Processing ID: 57211750056 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 1 papers.
   [73/103] Processing ID: 57789759900 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 1 papers.
   [74/103] Processing ID: 35798303400 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 15 papers.
   [75/103] Processing ID: 57202283774 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 27 papers.
   [76/103] Processing ID: 57201877528 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 17 papers.
   [77/103] Processing ID: 57395409700 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 21 papers.
   [78/103] Processing ID: 58679642300 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 8 papers.
   [79/103] Processing ID: 58038815400 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 9 papers.
   [80/103] Processing ID: 57193736439 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 26 papers.
   [81/103] Processing ID: 57865772100 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 16 papers.
   [82/103] Processing ID: 58949238400 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 18 papers.
   [83/103] Processing ID: 59512381200 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 10 papers.
   [84/103] Processing ID: 59512541500 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 5 papers.
   [85/103] Processing ID: 59512842000 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 6 papers.
   [86/103] Processing ID: 57201646218 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 5 papers.
   [87/103] Processing ID: 57204489182 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 15 papers.
   [88/103] Processing ID: 57201861861 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 7 papers.
   [89/103] Processing ID: 57201858789 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 1 papers.
   [90/103] Processing ID: 59864139300 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 4 papers.
   [91/103] Processing ID: 56766087800 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 9 papers.
   [92/103] Processing ID: 59150682800 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 6 papers.
   [93/103] Processing ID: 60285871600 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 1 papers.
   [94/103] Processing ID: 59150191200 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 5 papers.
   [95/103] Processing ID: 59730655400 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 1 papers.
   [96/103] Processing ID: 57205384339 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 15 papers.
   [97/103] Processing ID: 57200364969 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 25 papers.
   [98/103] Processing ID: 60333969100 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 1 papers.
   [99/103] Processing ID: 59306557700 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 12 papers.
   [100/103] Processing ID: 57199508187 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 16 papers.
   [101/103] Processing ID: 57210117456 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 24 papers.
   [102/103] Processing ID: 57200366518 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 8 papers.
   [103/103] Processing ID: 57680858500 (Cutoff: >None)
      ⬇️ Export Submitted
      ✅ Extracted 13 papers.
   ✅ Saved 1480 new papers to C:\Users\rizky\OneDrive\Dokumen\GitHub\Tugas_Akhir\scraping\file_tabulars\dosen_papers_scopus_raw.csv

,Scopus_Author_ID,Authors,Author IDs,Title,Year,Journal,Link,Abstract,Keywords,Document Type,DOI
0,57215981815,Ervin Yohannes; Yuni Yamasari; Aditya Prapanca...,57193503081; 57193733535; 57215981815; 5721189...,Educational Training on Business Management Us...,2024,2024 7th International Conference on Vocationa...,https://www.scopus.com/inward/record.uri?eid=2...,The business model has developed significantly...,application; business; cryptocurrency; educati...,Conference paper,10.1109/ICVEE63912.2024.10823784
1,57215981815,Widi Aribowo; Bambang Suprianto; Unit Three Ka...,57216862548; 8215287000; 57192095275; 57215981815,Dingo optimization algorithm for designing pow...,2023,Indonesian Journal of Electrical Engineering a...,https://www.scopus.com/inward/record.uri?eid=2...,The dingo optimization algorithm (DOA) adopts ...,Dingo optimization algorithm; Grasshopper opti...,Article,10.11591/ijeecs.v29.i1.pp1-7
2,57215981815,Widi Aribowo; Laith Abualigah; Diego Oliva; Mo...,57216862548; 57190984712; 55391699600; 5990058...,Enhancing photovoltaic parameters based on mod...,2025,Bulletin of Electrical Engineering and Informa...,https://www.scopus.com/inward/record.uri?eid=2...,This article presents a photovoltaic (PV) opti...,Innovation; Lévy flight optimization; Metaheur...,Article,10.11591/eei.v14i3.8977
3,57215981815,Setya Chendra Wibawa; D.S. Katmitasari; A. Pra...,57200035291; 57203288374; 57215981815; 5720056...,MobiAugmented reality: Studio lighting photogr...,2017,2017 International Conference on Advanced Comp...,https://www.scopus.com/inward/record.uri?eid=2...,This study is intended to create a simple phot...,augmented reality; photography; research and d...,Conference paper,10.1109/ICACSIS.2017.8355059
4,57215981815,Ervin Yohannes; Alfito Mulyono; Aditya Prapanc...,57193503081; 59544647100; 57215981815; 5548874...,Indonesia Traffic Sign Recognition Using a One...,2024,2024 7th International Conference on Vocationa...,https://www.scopus.com/inward/record.uri?eid=2...,Traffic is a key element in the transportation...,deep learning; detector; recognition; traffic ...,Conference paper,10.1109/ICVEE63912.2024.10824005
...,...,...,...,...,...,...,...,...,...,...,...
1475,57680858500,Choirun Nisak Aulina; Fajar Arianto; Agus Sali...,57208548639; 57680858500; 60001241000; 6021696...,Fostering Environmental Awareness and Social A...,2025,International Journal of Information and Educa...,https://www.scopus.com/inward/record.uri?eid=2...,—The purpose of this study is to analyze the e...,environmental awareness; social attitudes; tea...,Article,10.18178/ijiet.2025.15.11.2435
1476,57680858500,Nuril Huda; Mustaji; Fajar Arianto; Novadri Ayubi,57827392200; 57200364969; 57680858500; 5753749...,The Application of Blended Learning with a Com...,2022,International Journal of Emerging Technologies...,https://www.scopus.com/inward/record.uri?eid=2...,This study aims to analyze the effect of the b...,blended learning; community science technology...,Article,10.3991/ijet.v17i14.32927
1477,57680858500,Windiyati Nugroho; Mustaji; Fajar Arianto,58195446600; 57200364969; 57680858500,Twenty-First Century Instructional Design: Gui...,2023,Journal of Technical Education and Training,https://www.scopus.com/inward/record.uri?eid=2...,Instructional design can be challenging in a v...,competence; Instructional design; job skill; s...,Article,10.30880/jtet.2023.15.01.004
1478,57680858500,Dian Noer Asy'ari; Mustaji; Fajar Arianto,59704621900; 57200364969; 57680858500,Implementation of Digital Guided Discovery Lea...,2024,Proceedings - 2024 6th International Workshop ...,https://www.scopus.com/inward/record.uri?eid=2...,This study aims to analyze the implementation ...,boarding school; digital guided discovery lear...,Conference paper,10.1109/WAIE63876.2024.00040
1479,57680858500,Muhammad Hanif; Mustaji Mustaji; Fajar Arianto,57208133915; 57207956267; 57680858500,A Systematic Review of the Impact of Flipped L...,2025,Journal of Learning for Development,https://www.scopus.com/inward/record.uri?eid=2...,Flipped learning is an innovative instructiona...,college students; emotional attributes; flippe...,Article,10.56059/jl4d.v12i2.1495

---
### Step 2: Scopus Processing (Clean + Dedup + TLDR)
Process raw Scopus data: clean columns, remove duplicates (DOI + Title), enrich with TLDR summaries via Semantic Scholar API.

In [3]:
paper_pipeline.run_scopus_processing()

🔧 STEP 2: SCOPUS PROCESSING
==================================================

   📂 Loading Master Database: C:\Users\rizky\OneDrive\Dokumen\GitHub\Tugas_Akhir\scraping\file_tabulars\dosen_papers_scopus.csv
   🔄 Merging: New (1480) + Master (1149)
   🚀 Starting Processing Pipeline...
   🧹 Deduplicating 2629 records...
      - DOI Deduplication: Removed 1404 rows
      - Link (EID) Deduplication: Removed 73 rows
      - Title+Year Deduplication: Removed 1 rows
   ✅ Final Count: 1151 (Removed 1478 total)
🧹 Cleaning Author Names...
✨ Enriching with TLDR (Semantic Scholar)...
      ⚠️ Rate Limit (429). Sleeping 5s...
      ⚠️ Rate Limit (429). Sleeping 5s...
      ⚠️ Rate Limit (429). Sleeping 5s...
      ⚠️ Rate Limit (429). Sleeping 5s...
      ⚠️ Rate Limit (429). Sleeping 5s...
      ⚠️ Rate Limit (429). Sleeping 5s...
   ✅ Enriched 6 papers with TLDR
✨ Filtering Columns...
   ✅ Saved 1151 clean & enriched papers to C:\Users\rizky\OneDrive\Dokumen\GitHub\Tugas_Akhir\scraping\file_tabulars\dosen_papers_scopus.csv
   🧹 Cleaned up raw file: dosen_papers_scopus_raw.csv

,Authors,Author IDs,Title,Year,Journal,Link,Abstract,Keywords,Document Type,DOI,TLDR
0,Muhammad Rahulil; Yuni Yamasari; Ricky Eka Put...,60243635600; 57193733535; 56038565900; 5718969...,Rule-Based Adaptive Chatbot on WhatsApp for Vi...,2026,Journal of Electronics,https://www.scopus.com/inward/record.uri?eid=2...,Adapting learning methods to individual learni...,Adaptive System; Bayesian Inference; Chatbot; ...,Article,10.35882/jeeemi.v8i1.1215,A rule-based adaptive WhatsApp chatbot capable...
1,Naim Rochmawati; Chastine Fatichah; Bilqis Ama...,57195258934; 35811948800; 43260972600; 5719634...,Peritoneal Carcinomatosis Detection Based on I...,2026,IEEE Access,https://www.scopus.com/inward/record.uri?eid=2...,Peritoneal Carcinomatosis (PC) represents a se...,attention mechanism; CBAM; detection; peritone...,Article,10.1109/ACCESS.2025.3650190,
2,Hei-Chia Wang; Cendra Devayana Putra; Hsin-Tzu...,8514208600; 58922897800; 59938055300,Avoiding toxicity and prejudice in chatbots wi...,2026,Knowledge and Information Systems,https://www.scopus.com/inward/record.uri?eid=2...,We propose a method based on knowledge distill...,Adversarial attack; Chatbot; Knowledge distill...,Article,10.1007/s10115-025-02612-1,The results show that the proposed bi-long sho...
3,Ganjar Setyo Widodo; Ekohariadi; Yeni Anistyas...,57212678532; 57195553791; 53263227700; 5719506...,Collaborative assessment in education: A syste...,2026,Multidisciplinary Reviews,https://www.scopus.com/inward/record.uri?eid=2...,Collaborative assessment has seen rapid develo...,collaborative assessment; cultural gap; inclus...,Article,10.31893/multirev.2026241,
4,Wahyu Budi Sabtiawan; Wasis; Tri Rijanto; Yuri...,57195060766; 57195518718; 57216963152; 5721331...,An alternative assessment instrument for scien...,2026,Multidisciplinary Science Journal,https://www.scopus.com/inward/record.uri?eid=2...,Designing and implementing assessments are ess...,alternative assessment; content validity; gene...,Article,10.31893/multiscience.2026130,
...,...,...,...,...,...,...,...,...,...,...,...
1140,I Made Agus Setiawan; Elly M. Imah; Wisnu Jatmiko,55396194200; 54973804500; 8568432600,Arrhytmia classification using fuzzy-neuro gen...,2011,ICACSIS 2011 - 2011 International Conference o...,https://www.scopus.com/inward/record.uri?eid=2...,Automatic heart beats classification has attra...,,Conference paper,,
1141,Wisnu Jatmiko; W.P. Nulad; M.I. Elly; I. Made ...,8568432600; 39762386500; 54973804500; 55396194...,Heart beat classification using wavelet featur...,2011,WSEAS Transactions on Systems,https://www.scopus.com/inward/record.uri?eid=2...,Arrhytmia is one of the most crucial problem i...,Arrhythmia; Back-propagation; ECG; Electrocard...,Article,,This paper uses FLVQ to solve the weakness of ...
1142,Big Zaman; Wisnu Jatmiko; Adi Wibowo; Elly Mat...,55013255900; 8568432600; 57205972690; 54973804500,Implementation vehicle classification on distr...,2011,ICACSIS 2011 - 2011 International Conference o...,https://www.scopus.com/inward/record.uri?eid=2...,Distributed Traffic System Control System is a...,,Conference paper,,
1143,A. Febrian; M. Fajar; M.I. Tawakal; E.M. Imah;...,36987333000; 58485126500; 55014602700; 5497380...,FNLVQ design and implementation in FPGA to est...,2011,ICACSIS 2011 - 2011 International Conference o...,https://www.scopus.com/inward/record.uri?eid=2...,"Embedded systems are more popular these days, ...",,Conference paper,,
1144,Nanang Husin,55008449900,Internet user behavior analysis in online shop...,2011,ICACSIS 2011 - 2011 International Conference o...,https://www.scopus.com/inward/record.uri?eid=2...,"Currently, internet users in Indonesia have st...",,Conference paper,,

---
### Step 3: Supabase Insert (Upsert + Link)
Upload cleaned Scopus papers to Supabase. Automatically links papers to lecturers via `Author IDs` column.

In [3]:
paper_pipeline.run_supabase_insert()

🚀 STEP 3: SUPABASE INSERT
==================================================
   📂 Loading Cleaned Papers...
   📝 Total Rows: 1151
✅ Supabase Client Connected to https://wfjzdhaaldwyiajbyzln.supabase.co

   🚀 Upserting Papers to Supabase...
🚀 Upserting 1085 papers (by DOI)...
   ✅ Batch 1: 100 papers
   ✅ Batch 2: 100 papers
   ✅ Batch 3: 100 papers
   ✅ Batch 4: 100 papers
   ✅ Batch 5: 100 papers
   ✅ Batch 6: 100 papers
   ✅ Batch 7: 100 papers
   ✅ Batch 8: 100 papers
   ✅ Batch 9: 100 papers
   ✅ Batch 10: 100 papers
   ✅ Batch 11: 85 papers
✅ Total: 1085 papers upserted. (66 skipped)

   🔗 Linking Papers to Lecturers...
🔗 Linking 1151 paper records to lecturers...
   ⚠️ No new links to insert.

   ✅ Insertion & Linking Complete!

---
### Step 4: Google Scholar Scraping (SerpAPI)
Scrape papers from Google Scholar via SerpAPI (`google_scholar_author` engine).
Performs cross-deduplication against existing Scopus papers (exact + fuzzy matching).
Saves raw data with empty enrichment columns to `dosen_papers_scholar_raw.csv`.

In [2]:
paper_pipeline.run_scholar_scraping()

📖 STEP 4: GOOGLE SCHOLAR SCRAPING (3-Phase: Scrape → Dedup → Match)
======================================================================
   🎯 124 dosen with Scholar ID.


==================================================
📡 PHASE 1: PURE SCRAPE (No Filter, Auto-Save)
==================================================
[1/124] Aditya Prapanca, S.T., M.Kom. (WdhKN0sAAAAJ)...
      📄 90 papers fetched.
      💾 [Auto-Save] 90 papers saved to temp.
[2/124] Anita Qoiriah, S.Kom., M.Kom. (N6RJilIAAAAJ)...
      📄 113 papers fetched.
      💾 [Auto-Save] 203 papers saved to temp.
[3/124] Dr. Yuni Yamasari, S.Kom., M.Kom.Dosen (hn5jrnAAAAAJ)...
      📄 131 papers fetched.
      💾 [Auto-Save] 334 papers saved to temp.
[4/124] Agus Prihanto, S.T., M.Kom. (-_VNTSIAAAAJ)...
      📄 98 papers fetched.
      💾 [Auto-Save] 432 papers saved to temp.
[5/124] Dr. Ir. Ricky Eka Putra, S.Kom., M.Kom.Dosen (cPj-iOIAAAAJ)...
      📄 119 papers fetched.
      💾 [Auto-Save] 551 papers saved to temp.
[6/124] I Made Suartana, S.Kom., M.Kom. (RvG7jG4AAAAJ)...
      📄 110 papers fetched.
      💾 [Auto-Save] 661 papers saved to temp.
[7/124] Naim Rochmawati, S.Kom., M.T. (8wFXNjYAAAAJ)...
      📄 80 papers fetched.
      💾 [Auto-Save] 741 papers saved to temp.
[8/124] Paramitha Nerisafitra, S.ST., M.Kom. (Em3aIV0AAAAJ)...
      📄 60 papers fetched.
      💾 [Auto-Save] 801 papers saved to temp.
[9/124] Ronggo Alit, S.Kom., M.M., M.T. (fkxhjZ4AAAAJ)...
      📄 98 papers fetched.
      💾 [Auto-Save] 899 papers saved to temp.
[10/124] Ervin Yohannes, S.Kom., M.Kom., M.Sc., Ph.D.Dosen (nyyfjCgAAAAJ)...
      📄 30 papers fetched.
      💾 [Auto-Save] 929 papers saved to temp.
[11/124] Farhanna Mari, S.Kom., M.Kom. (LeRoniwAAAAJ)...
      📄 33 papers fetched.
      💾 [Auto-Save] 962 papers saved to temp.
[12/124] Rifqi Abdillah, S.Tr.T., M.Kom. (nyyfjCgAAAAJ)...
      📄 30 papers fetched.
      💾 [Auto-Save] 992 papers saved to temp.
[13/124] Dr. Wiyli Yustanti, S.Si., M.Kom.Dosen (CxdwNaYAAAAJ)...
      📄 116 papers fetched.
      💾 [Auto-Save] 1108 papers saved to temp.
[14/124] Dwi Fatrianto Suyatno, S.Kom., M.Kom. (OffRzhoAAAAJ)...
      📄 74 papers fetched.
      💾 [Auto-Save] 1182 papers saved to temp.
[15/124] Aries Dwi Indriyanti, S.Kom., M.Kom. (Jzuk6doAAAAJ)...
      ⚠️ SerpAPI return kosong (attempt 1), retry in 3s...
      ⚠️ SerpAPI return kosong (attempt 2), retry in 3s...
      🔄 Retry 2 berhasil (100 articles)
      📄 161 papers fetched.
      💾 [Auto-Save] 1343 papers saved to temp.
[16/124] Ardhini Warih Utami, S.Kom., M.Kom. (ZBAnb64AAAAJ)...
      📄 66 papers fetched.
      💾 [Auto-Save] 1409 papers saved to temp.
[17/124] Rahadian Bisma, S.Kom., M.Kom. (eEtHoOAAAAAJ)...
      📄 60 papers fetched.
      💾 [Auto-Save] 1469 papers saved to temp.
[18/124] Ghea Sekar Palupi, S.Kom., M.I.M. (4d_6xxEAAAAJ)...
      📄 37 papers fetched.
      💾 [Auto-Save] 1506 papers saved to temp.
[19/124] Bonda Sisephaputra, M. Kom. (psg8hdoAAAAJ)...
      📄 44 papers fetched.
      💾 [Auto-Save] 1550 papers saved to temp.
[20/124] Berlian Maulidya Izzati, S.Kom. M.Kom. (_VFGVQQAAAAJ)...
      📄 32 papers fetched.
      💾 [Auto-Save] 1582 papers saved to temp.
[21/124] Anggraeni Widya Purwita, M.Kom. (jPKU5cAAAAAJ)...
      📄 14 papers fetched.
      💾 [Auto-Save] 1596 papers saved to temp.
[22/124] Monica Cinthya, M.Kom. (hrVTt4kAAAAJ)...
      📄 12 papers fetched.
      💾 [Auto-Save] 1608 papers saved to temp.
[23/124] Cendra Devayana Putra, S.Kom., M.IM. (XdEn69YAAAAJ)...
      📄 31 papers fetched.
      💾 [Auto-Save] 1639 papers saved to temp.
[24/124] Erik Rahman, S.Kom., M.M.S.I. (ZjPpHWsAAAAJ)...
      📄 24 papers fetched.
      💾 [Auto-Save] 1663 papers saved to temp.
[25/124] Prof. Dr. Ekohariadi, M.Pd. (YADiqesAAAAJ)...
      📄 24 papers fetched.
      💾 [Auto-Save] 1687 papers saved to temp.
[26/124] Drs. Bambang Sujatmiko, M.T. (qtFw9UMAAAAJ)...
      📄 132 papers fetched.
      💾 [Auto-Save] 1819 papers saved to temp.
[27/124] Dr. Tri Rijanto, M.Pd., M.T. (z7RWDi0AAAAJ)...
      📄 250 papers fetched.
      💾 [Auto-Save] 2069 papers saved to temp.
[28/124] Dr. Yeni Anistyasari, S.Pd., M.Kom. (IJIEntMAAAAJ)...
      📄 182 papers fetched.
      💾 [Auto-Save] 2251 papers saved to temp.
[29/124] I Gusti Lanang Putra Eka Prismana, S.Kom., M.Kom. (_n2j0ZAAAAAJ)...
      📄 101 papers fetched.
      💾 [Auto-Save] 2352 papers saved to temp.
[30/124] Rindu Puspita Wibawa, S.Kom., M.Kom. (Hl6bqU8AAAAJ)...
      📄 50 papers fetched.
      💾 [Auto-Save] 2402 papers saved to temp.
[31/124] Martini Dwi Endah Susanti, S.Kom., M.Kom. (q24bD6AAAAAJ)...
      📄 3 papers fetched.
      💾 [Auto-Save] 2405 papers saved to temp.
[32/124] Ramadhan Cakra Wibawa, S.Pd., M.Kom. (Em3aIV0AAAAJ)...
      📄 60 papers fetched.
      💾 [Auto-Save] 2465 papers saved to temp.
[33/124] Harun Al Rosyid, S.T., M.T. (yXy6kW0AAAAJ)...
      📄 18 papers fetched.
      💾 [Auto-Save] 2483 papers saved to temp.
[34/124] Rizky Basatha, S.Pd., M.MT. (FZ00CQ8AAAAJ)...
      ⚠️ SerpAPI return kosong (attempt 1), retry in 3s...
      ⚠️ SerpAPI return kosong (attempt 2), retry in 3s...
      🔄 Retry 2 berhasil (82 articles)
      📄 82 papers fetched.
      💾 [Auto-Save] 2565 papers saved to temp.
[35/124] Riza Akhsani Setyo Prayoga, S.Kom., M.MT. (34CwHgkAAAAJ)...
      📄 48 papers fetched.
      💾 [Auto-Save] 2613 papers saved to temp.
[36/124] Muhammad Sonhaji Akbar, S.Pd., M.Kom. (cY1QGVEAAAAJ)...
      📄 20 papers fetched.
      💾 [Auto-Save] 2633 papers saved to temp.
[37/124] Ersha Aisyah Elfaiz, S.Si., M.T.I. (VNrCn4gAAAAJ)...
      📄 17 papers fetched.
      💾 [Auto-Save] 2650 papers saved to temp.
[38/124] Nisa Dwi Septiyanti, S.Kom., M.Pd., M.Sc. (VwvPnrcAAAAJ)...
      📄 44 papers fetched.
      💾 [Auto-Save] 2694 papers saved to temp.
[39/124] Prof. Dr. Bambang Suprianto,  M.T. (j8HRV1wAAAAJ)...
      ⚠️ SerpAPI return kosong (attempt 1), retry in 3s...
      ⚠️ SerpAPI return kosong (attempt 2), retry in 3s...
      🔄 Retry 2 berhasil (100 articles)
      📄 244 papers fetched.
      💾 [Auto-Save] 2938 papers saved to temp.
[40/124] Prof. Dr. I Gusti Putu Asto Buditjahjanto, S.T., M.T.Dosen (yObeL8gAAAAJ)...
      📄 159 papers fetched.
      💾 [Auto-Save] 3097 papers saved to temp.
[41/124] Prof. Dr. Tri Wrahatnolo, M.Pd.  M.T. (L6O1lvkAAAAJ)...
      📄 8 papers fetched.
      💾 [Auto-Save] 3105 papers saved to temp.
[42/124] Prof. Dr. Joko, M.Pd., M.T. (n7IAKI0AAAAJ)...
      📄 45 papers fetched.
      💾 [Auto-Save] 3150 papers saved to temp.
[43/124] Unit Three Kartini, S.T., M.T.  Ph. D (S6IJ51cAAAAJ)...
      ⚠️ SerpAPI return kosong (attempt 1), retry in 3s...
      ⚠️ SerpAPI return kosong (attempt 2), retry in 3s...
      🔄 Retry 2 berhasil (100 articles)
      📄 124 papers fetched.
      💾 [Auto-Save] 3274 papers saved to temp.
[44/124] Prof. Dr. Lilik Anifah, S.T., M.T. (6MXDzBQAAAAJ)...
      📄 214 papers fetched.
      💾 [Auto-Save] 3488 papers saved to temp.
[45/124] Dr. Ir. Lusia Rakhmawati, S.T.,  M.T. (nWPONc8AAAAJ)...
      📄 105 papers fetched.
      💾 [Auto-Save] 3593 papers saved to temp.
[46/124] Prof. Dr. Nurhayati, S.T., M.T. (AYI1rosAAAAJ)...
      📄 114 papers fetched.
      💾 [Auto-Save] 3707 papers saved to temp.
[47/124] Dr. Raden Roro Hapsari Peni  Agustin T, S.Si., M.T. (N40Vh64AAAAJ)...
      📄 72 papers fetched.
      💾 [Auto-Save] 3779 papers saved to temp.
[48/124] Pradini Puspitaningayu, S.T.,  M.T., Ph. D (A9L19RMAAAAJ)...
      📄 76 papers fetched.
      💾 [Auto-Save] 3855 papers saved to temp.
[49/124] Dr. Puput Wanarti Rusimamto, S.T., M.T. (LsydBAMAAAAJ)...
      📄 237 papers fetched.
      💾 [Auto-Save] 4092 papers saved to temp.
[50/124] Dr. Subuh Isnur Haryudo, S.T.,  M.T. (p1pK7E4AAAAJ)...
      📄 208 papers fetched.
      💾 [Auto-Save] 4300 papers saved to temp.
[51/124] Dr. Ir. Nur Kholis, S.T., M.T. (hjllQ9gAAAAJ)...
      📄 148 papers fetched.
      💾 [Auto-Save] 4448 papers saved to temp.
[52/124] Endryansyah, S.T., M.T. (9BWyE0UAAAAJ)...
      ⚠️ SerpAPI return kosong (attempt 1), retry in 3s...
      ⚠️ SerpAPI return kosong (attempt 2), retry in 3s...
      🔄 Retry 2 berhasil (100 articles)
      📄 134 papers fetched.
      💾 [Auto-Save] 4582 papers saved to temp.
[53/124] Dr. Farid Baskoro, S.T., M.T. (Tp_X_bYAAAAJ)...
      📄 146 papers fetched.
      💾 [Auto-Save] 4728 papers saved to temp.
[54/124] Rifqi Firmansyah, S.T., M.T.,  Ph.D. (sHANI1gAAAAJ)...
      📄 83 papers fetched.
      💾 [Auto-Save] 4811 papers saved to temp.
[55/124] Arif Widodo, S.T., M.Sc. (RES4QIQAAAAJ)...
      📄 72 papers fetched.
      💾 [Auto-Save] 4883 papers saved to temp.
[56/124] Miftahur Rohman, S.T., M.T. (TB0QfMoAAAAJ)...
      📄 11 papers fetched.
      💾 [Auto-Save] 4894 papers saved to temp.
[57/124] Parama Diptya Widayaka, S.ST.,  M.T. (nbtuM4IAAAAJ)...
      ⚠️ SerpAPI return kosong (attempt 1), retry in 3s...
      ⚠️ SerpAPI return kosong (attempt 2), retry in 3s...
      🔄 Retry 2 berhasil (50 articles)
      📄 50 papers fetched.
      💾 [Auto-Save] 4944 papers saved to temp.
[58/124] Mahendra Widyartono, S.T., M.T. (6f4j4TYAAAAJ)...
      📄 82 papers fetched.
      💾 [Auto-Save] 5026 papers saved to temp.
[59/124] Dr. Widi Aribowo, S.T., M.T. (lmlBHlsAAAAJ)...
      📄 177 papers fetched.
      💾 [Auto-Save] 5203 papers saved to temp.
[60/124] Reza Rahmadian, S.ST., M. EngSc (1hm7MM8AAAAJ)...
      📄 65 papers fetched.
      💾 [Auto-Save] 5268 papers saved to temp.
[61/124] Aditya Chandra Hermawan, S.ST.,  M.T. (aW1lSOYAAAAJ)...
      📄 9 papers fetched.
      💾 [Auto-Save] 5277 papers saved to temp.
[62/124] Sayyidul Aulia Alamsyah, S.T., M.T. (MnI3Tm0AAAAJ)...
      📄 20 papers fetched.
      💾 [Auto-Save] 5297 papers saved to temp.
[63/124] Yandhika Surya Akbar Gumilang, S.T., M.T. (y_OiarcAAAAJ)...
      📄 26 papers fetched.
      💾 [Auto-Save] 5323 papers saved to temp.
[64/124] Hesti Khuzaimah Nurul Yusufiyah,  S.Si., M.Eng. (Mr22rjsAAAAJ)...
      ⚠️ SerpAPI return kosong (attempt 1), retry in 3s...
      ⚠️ SerpAPI return kosong (attempt 2), retry in 3s...
      🔄 Retry 2 berhasil (12 articles)
      📄 12 papers fetched.
      💾 [Auto-Save] 5335 papers saved to temp.
[65/124] Ir. Wahyu Sasongko Putro, B.Eng., M.Sc.,IPM., ASEAN Eng., APEC Eng. (NO8mJucAAAAJ)...
      📄 27 papers fetched.
      💾 [Auto-Save] 5362 papers saved to temp.
[66/124] Namira Roudlotul Jannah, S.T., M.T. (C_EGqeMAAAAJ)...
      📄 5 papers fetched.
      💾 [Auto-Save] 5367 papers saved to temp.
[67/124] Dr. Elly Matul Imah, M.Kom. (Head of Study Program) (tzjThtIAAAAJ)...
      ⚠️ SerpAPI return kosong (attempt 1), retry in 3s...
      ⚠️ SerpAPI return kosong (attempt 2), retry in 3s...
      🔄 Retry 2 berhasil (84 articles)
      📄 84 papers fetched.
      💾 [Auto-Save] 5451 papers saved to temp.
[68/124] Riskyana Dewi Intan P, M.Kom. (DiBTIz4AAAAJ)...
      📄 23 papers fetched.
      💾 [Auto-Save] 5474 papers saved to temp.
[69/124] Fadhilah Qalbi Annisa, S.T., M.Sc. (AaC4eAwAAAAJ)...
      📄 14 papers fetched.
      💾 [Auto-Save] 5488 papers saved to temp.
[70/124] Harmon Prayogi, M.Sc. (RNJ3vNQAAAAJ)...
      📄 14 papers fetched.
      💾 [Auto-Save] 5502 papers saved to temp.
[71/124] Ike Fitriyaningsih, S.Si., M.Si. (wEGsLv4AAAAJ)...
      📄 11 papers fetched.
      💾 [Auto-Save] 5513 papers saved to temp.
[72/124] Dr. Atik Wintarti, M.Kom. (lFCI_vsAAAAJ)...
      📄 72 papers fetched.
      💾 [Auto-Save] 5585 papers saved to temp.
[73/124] Ibnu Febry Kurniawan, S.Kom, M.Sc., Ph.D. (BIrtbD8AAAAJ)...
      📄 22 papers fetched.
      💾 [Auto-Save] 5607 papers saved to temp.
[74/124] Yuliani Puji Astuti, S.Si., M.Si. (Tz8EfXcAAAAJ)...
      📄 68 papers fetched.
      💾 [Auto-Save] 5675 papers saved to temp.
[75/124] Hasanuddin Al-Habib, S.Si., M.Si. (AX-w0AEAAAAJ)...
      📄 12 papers fetched.
      💾 [Auto-Save] 5687 papers saved to temp.
[76/124] Ulfa Siti Nuraini, S.Stat., M.Stat. (q-sbahIAAAAJ)...
      📄 21 papers fetched.
      💾 [Auto-Save] 5708 papers saved to temp.
[77/124] Dinda Galuh Guminta, S.Stat., M.Stat. (_ecYpyYAAAAJ)...
      📄 3 papers fetched.
      💾 [Auto-Save] 5711 papers saved to temp.
[78/124] Kartika Chandra Dewi, S.Si., M.Si. (Y7qO6YYAAAAJ)...
      📄 4 papers fetched.
      💾 [Auto-Save] 5715 papers saved to temp.
[79/124] Yuni Rosita Dewi, S.Si., M.Si. (i0pkJZoAAAAJ)...
      📄 22 papers fetched.
      💾 [Auto-Save] 5737 papers saved to temp.
[80/124] Dr. Heri Purnawan, S.Si., M.Si. (5uDKOUMAAAAJ)...
      📄 22 papers fetched.
      💾 [Auto-Save] 5759 papers saved to temp.
[81/124] Moh. Khoridatul Huda, S.Pd., M.Si., Ph.D. (b4_EdJYAAAAJ)...
      ⚠️ SerpAPI return kosong (attempt 1), retry in 3s...
      ⚠️ SerpAPI return kosong (attempt 2), retry in 3s...
      🔄 Retry 2 berhasil (41 articles)
      📄 41 papers fetched.
      💾 [Auto-Save] 5800 papers saved to temp.
[82/124] Belgis Ainatul Iza, S.Si, M.Mat. (Y4YoRwUAAAAJ)...
      📄 7 papers fetched.
      💾 [Auto-Save] 5807 papers saved to temp.
[83/124] Siska Puspitaningsih, S.Kom., M.Kom. (jJBtZPgAAAAJ)...
      📄 17 papers fetched.
      💾 [Auto-Save] 5824 papers saved to temp.
[84/124] Nurul Laili, S.Pd., M.Sc. (pCyzpjgAAAAJ)...
      📄 2 papers fetched.
      💾 [Auto-Save] 5826 papers saved to temp.
[85/124] Hujjatullah Fazlurrahman, S.E., M.B.A. (4Yhmpg0AAAAJ)...
      📄 64 papers fetched.
      💾 [Auto-Save] 5890 papers saved to temp.
[86/124] Achmad Kautsar, S.E., M.M. (bTjH6IgAAAAJ)...
      📄 109 papers fetched.
      💾 [Auto-Save] 5999 papers saved to temp.
[87/124] Hafid Kholidi Hadi, S.E., M.SM. (W7ncZRgAAAAJ)...
      📄 67 papers fetched.
      💾 [Auto-Save] 6066 papers saved to temp.
[88/124] Ika Diyah Candra Arifah, S.E., M.Com. (6ifThF0AAAAJ)...
      📄 65 papers fetched.
      💾 [Auto-Save] 6131 papers saved to temp.
[89/124] Riska Dhenabayu, S.Kom., M.M. (ZRCJXO0AAAAJ)...
      📄 41 papers fetched.
      💾 [Auto-Save] 6172 papers saved to temp.
[90/124] Fresha Kharisma, S.E., M.SM. (DrE0Lf8AAAAJ)...
      ⚠️ SerpAPI return kosong (attempt 1), retry in 3s...
      ⚠️ SerpAPI return kosong (attempt 2), retry in 3s...
      🔄 Retry 2 berhasil (34 articles)
      📄 34 papers fetched.
      💾 [Auto-Save] 6206 papers saved to temp.
[91/124] Renny Sari Dewi, S.Kom., M.Kom. (4VXQFKYAAAAJ)...
      ⚠️ SerpAPI return kosong (attempt 1), retry in 3s...
      ⚠️ SerpAPI return kosong (attempt 2), retry in 3s...
      🔄 Retry 2 berhasil (100 articles)
      ⚠️ SerpAPI return kosong (attempt 1), retry in 3s...
      ⚠️ SerpAPI return kosong (attempt 2), retry in 3s...
      🔄 Retry 2 berhasil (1 articles)
      📄 101 papers fetched.
      💾 [Auto-Save] 6307 papers saved to temp.
[92/124] Anita Safitri, S.Kom., M.Kom. (b81qaDkAAAAJ)...
      📄 29 papers fetched.
      💾 [Auto-Save] 6336 papers saved to temp.
[93/124] Dr. Nanang Hoesen. H. A., S.T., M.T.I. (Smb2eg8AAAAJ)...
      📄 48 papers fetched.
      💾 [Auto-Save] 6384 papers saved to temp.
[94/124] Muhammad Fajar Wahyudi Rahman, S.E. M.M. (dfwr-2YAAAAJ)...
      📄 55 papers fetched.
      💾 [Auto-Save] 6439 papers saved to temp.
[95/124] Dr. Ratih Amelia, S.E., M.M. (-BuJoD0AAAAJ)...
      📄 12 papers fetched.
      💾 [Auto-Save] 6451 papers saved to temp.
[96/124] Nadia Nur Thahirrah, S.E., M.S.M. (DsVi_OAAAAAJ)...
      ⚠️ SerpAPI return kosong (attempt 1), retry in 3s...
      ⚠️ SerpAPI return kosong (attempt 2), retry in 3s...
      🔄 Retry 2 berhasil (16 articles)
      📄 16 papers fetched.
      💾 [Auto-Save] 6467 papers saved to temp.
[97/124] Dr. Dhiyan Septa Wihara, S.P., M.M. (n7ykK-IAAAAJ)...
      📄 56 papers fetched.
      💾 [Auto-Save] 6523 papers saved to temp.
[98/124] Dr. Muhammad Fachmi, S.E., M.M. (5nAJx9wAAAAJ)...
      📄 50 papers fetched.
      💾 [Auto-Save] 6573 papers saved to temp.
[99/124] Achmad Fitro, S.Kom., M.Kom. (itwnm-AAAAAJ)...
      📄 58 papers fetched.
      💾 [Auto-Save] 6631 papers saved to temp.
[100/124] Muhammad Febrilian Dwi Syahputra, S.Kom., M.Kom. (2lw6P3IAAAAJ)...
      📄 11 papers fetched.
      💾 [Auto-Save] 6642 papers saved to temp.
[101/124] Dana Azizah Rahmat, S.T., M.T., MBA. (UL2-upoAAAAJ)...
      📄 8 papers fetched.
      💾 [Auto-Save] 6650 papers saved to temp.
[102/124] Danang Ary Dewangga, S.Kom., M.SM. (ne31is4AAAAJ)...
      📄 3 papers fetched.
      💾 [Auto-Save] 6653 papers saved to temp.
[103/124] Rakha Asyrofi, S.ST., M.Kom. (o4zdesUAAAAJ)...
      📄 15 papers fetched.
      💾 [Auto-Save] 6668 papers saved to temp.
[104/124] Dodik Arwin Dermawan, S.ST., S.T., M.T. (Thp8jg0AAAAJ)...
      📄 155 papers fetched.
      💾 [Auto-Save] 6823 papers saved to temp.
[105/124] Asmunin, S.Kom., M.Kom. (7EQjv9wAAAAJ)...
      📄 67 papers fetched.
      💾 [Auto-Save] 6890 papers saved to temp.
[106/124] Andi Iwan Nurhidayat, S.Kom., M.T. (t5f89iIAAAAJ)...
      ⚠️ SerpAPI return kosong (attempt 1), retry in 3s...
      ⚠️ SerpAPI return kosong (attempt 2), retry in 3s...
      🔄 Retry 2 berhasil (4 articles)
      📄 4 papers fetched.
      💾 [Auto-Save] 6894 papers saved to temp.
[107/124] Ari Kurniawan, S.Kom., M.T. (JsEkeOsAAAAJ)...
      📄 6 papers fetched.
      💾 [Auto-Save] 6900 papers saved to temp.
[108/124] Salamun Rohman Nudin, S.Kom., M.Kom. (wlGfsB0AAAAJ)...
      📄 89 papers fetched.
      💾 [Auto-Save] 6989 papers saved to temp.
[109/124] I Gde Agung Sri Sidhimantra, S.Kom., M.Kom. (TAAC1-AAAAAJ)...
      📄 30 papers fetched.
      💾 [Auto-Save] 7019 papers saved to temp.
[110/124] Rosita, S.Pd., M.Pd. (nVac1BcAAAAJ)...
      📄 7 papers fetched.
      💾 [Auto-Save] 7026 papers saved to temp.
[111/124] Faris Abdi El Hakim, S.Kom., M.Tr.Kom. (-gGGkMcAAAAJ)...
      📄 11 papers fetched.
      💾 [Auto-Save] 7037 papers saved to temp.
[112/124] Binti Kholifah, S.Kom., M.Tr.Kom. (MeGE8WAAAAAJ)...
      📄 12 papers fetched.
      💾 [Auto-Save] 7049 papers saved to temp.
[113/124] Dimas Novian Aditia Syahputra, S.Tr.T., M.Tr.T. (-tpBKawAAAAJ)...
      📄 16 papers fetched.
      💾 [Auto-Save] 7065 papers saved to temp.
[114/124] Moch Deny Pratama, S.Tr.Kom., M.Kom. (pb3-UjwAAAAJ)...
      📄 17 papers fetched.
      💾 [Auto-Save] 7082 papers saved to temp.
[115/124] M Adamu Islam Mashuri, S.Tr.T., M.Tr.Kom. (wwhACXoAAAAJ)...
      📄 16 papers fetched.
      💾 [Auto-Save] 7098 papers saved to temp.
[116/124] Dr. Fitria, S.Pd., M.Pd. (OwdLKtQAAAAJ)...
      📄 6 papers fetched.
      💾 [Auto-Save] 7104 papers saved to temp.
[117/124] Moch. Badrus Sholeh, S.Kom., M.Kom. (EBgY5K0AAAAJ)...
      📄 6 papers fetched.
      💾 [Auto-Save] 7110 papers saved to temp.
[118/124] Prof. Dr. Mustaji, M.Pd. (zDgqPOsAAAAJ)...
      📄 248 papers fetched.
      💾 [Auto-Save] 7358 papers saved to temp.
[119/124] Prof.Dr. Rusijono, M.Pd. (p4gdgRgAAAAJ)...
      📄 132 papers fetched.
      💾 [Auto-Save] 7490 papers saved to temp.
[120/124] Prof. Dr. Siti Masitoh, M.Pd. (AjvtBWIAAAAJ)...
      📄 105 papers fetched.
      💾 [Auto-Save] 7595 papers saved to temp.
[121/124] Prof.Dr.Yatim Riyanto,M.Pd. (6RBIukkAAAAJ)...
      📄 235 papers fetched.
      💾 [Auto-Save] 7830 papers saved to temp.
[122/124] Dr. Bachtiar Syaiful Bachri, M.Pd (ZhJ08JkAAAAJ)...
      📄 223 papers fetched.
      💾 [Auto-Save] 8053 papers saved to temp.
[123/124] Dr. Andi Mariono, M.Pd (Iq3gzh4AAAAJ)...
      ⚠️ SerpAPI return kosong (attempt 1), retry in 3s...
      ⚠️ SerpAPI return kosong (attempt 2), retry in 3s...
      🔄 Retry 2 berhasil (68 articles)
      📄 168 papers fetched.
      💾 [Auto-Save] 8221 papers saved to temp.
[124/124] Dr. Fajar Arianto, M.Pd. (MZCJPuIAAAAJ)...
      📄 208 papers fetched.
      💾 [Auto-Save] 8429 papers saved to temp.

   💾 Phase 1 Complete: 8429 total raw papers (165 API calls)

==================================================
🔍 PHASE 2: BATCH DEDUP (Scopus + Cross-Dosen)
==================================================
   📚 Loaded 1147 Scopus titles for dedup.
   🔄 Scopus exact dedup: 1197 papers removed.
   🔄 Cross-dosen exact dedup: 1503 papers removed.
   🔄 Fuzzy dedup on 5729 remaining papers...
   🔄 Fuzzy dedup: 156 papers removed.


,Authors,Author IDs,Title,Year,Journal,Link,Abstract,Keywords,Document Type,DOI,TLDR,citation_id,scholar_id,dosen,source
0,Aditya Prapanca,WdhKN0sAAAAJ,Perancangan Dan Implementasi Sistem Penyimpana...,2026,Journal of Informatics and Computer Science (J...,https://scholar.google.com/citations?view_op=v...,,,,,,WdhKN0sAAAAJ:4hFrxpcac9AC,WdhKN0sAAAAJ,"Aditya Prapanca, S.T., M.Kom.",scholar
1,Aditya Prapanca,WdhKN0sAAAAJ,Pengembangan E-Modul Berbasis Web Dengan Model...,2026,IT-Edu: Jurnal Information Technology and Educ...,https://scholar.google.com/citations?view_op=v...,,,,,,WdhKN0sAAAAJ:a9-T7VOCCH8C,WdhKN0sAAAAJ,"Aditya Prapanca, S.T., M.Kom.",scholar
2,"Yuni Yamasari, Anita Qoiriah, Ricky Eka Putra,...",WdhKN0sAAAAJ;hn5jrnAAAAAJ;N6RJilIAAAAJ;cPj-iOI...,Pelatihan Aplikasi Komputer untuk Penulisan Il...,2025,PengabdianMu: Jurnal Ilmiah Pengabdian kepada ...,https://scholar.google.com/citations?view_op=v...,,,,,,WdhKN0sAAAAJ:LO7wyVUgiFcC,WdhKN0sAAAAJ,"Aditya Prapanca, S.T., M.Kom.",scholar
3,Aditya Prapanca,WdhKN0sAAAAJ,Pengembangan Sistem Rekomendasi Film Berbasis ...,2025,Journal of Informatics and Computer Science (J...,https://scholar.google.com/citations?view_op=v...,,,,,,WdhKN0sAAAAJ:8d8msizDQcsC,WdhKN0sAAAAJ,"Aditya Prapanca, S.T., M.Kom.",scholar
4,Aditya Prapanca,WdhKN0sAAAAJ,Implementasi Algoritma C5. 0 Pada Klasifikasi ...,2025,Journal of Informatics and Computer Science (J...,https://scholar.google.com/citations?view_op=v...,,,,,,WdhKN0sAAAAJ:_FM0Bhl9EiAC,WdhKN0sAAAAJ,"Aditya Prapanca, S.T., M.Kom.",scholar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5568,Fajar Arianto,MZCJPuIAAAAJ,PLASMA TOKAMAK SEBAGAI PEMBANGKIT ENERGI MASA ...,,,https://scholar.google.com/citations?view_op=v...,,,,,,MZCJPuIAAAAJ:u_35RYKgDlwC,MZCJPuIAAAAJ,"Dr. Fajar Arianto, M.Pd.",scholar
5569,"Fajar Arianto, Cendra Devayana Putra, Rifqi Ab...",MZCJPuIAAAAJ;XdEn69YAAAAJ;nyyfjCgAAAAJ,Implementation of Online Collaborative Learnin...,,,https://scholar.google.com/citations?view_op=v...,,,,,,MZCJPuIAAAAJ:SeFeTyx0c_EC,MZCJPuIAAAAJ,"Dr. Fajar Arianto, M.Pd.",scholar
5570,Fajar Arianto,MZCJPuIAAAAJ,THE CORRELATION BETWEEN ADMINISTRATIVE SERVICE...,,,https://scholar.google.com/citations?view_op=v...,,,,,,MZCJPuIAAAAJ:O3NaXMp0MMsC,MZCJPuIAAAAJ,"Dr. Fajar Arianto, M.Pd.",scholar
5571,Fajar Arianto,MZCJPuIAAAAJ,The Impact of Learning Independence on Higher ...,,,https://scholar.google.com/citations?view_op=v...,,,,,,MZCJPuIAAAAJ:k_IJM867U9cC,MZCJPuIAAAAJ,"Dr. Fajar Arianto, M.Pd.",scholar
5572,Fajar Arianto,MZCJPuIAAAAJ,Ulfatun Nikmah,,,https://scholar.google.com/citations?view_op=v...,,,,,,MZCJPuIAAAAJ:e5wmG9Sq2KIC,MZCJPuIAAAAJ,"Dr. Fajar Arianto, M.Pd.",scholar

---
### Step 5: Scholar Enrichment (Keywords, Abstract, DOI, TLDR)
Enrich Scholar papers using a cost-optimized multi-source strategy:

1. **CrossRef API (FREE)** → DOI lookup by title (validated with 95% fuzzy match)
2. **DOI Redirect & Publisher Scraping** → Follow DOI to publisher page for abstract and keywords
3. **BrightData Proxy (PAID Fallback)** → Only if CrossRef fails: resolve Scholar citation page using exact notebook logic (PDF → Title → Cluster)
4. **Specialized EBSCO Fix** → Direct extraction of subjects/abstract from EBSCO's Next.js metadata
5. **OpenAlex API (FREE)** → Keyword/concept fallback
6. **Semantic Scholar (FREE)** → TLDR summary

Input: `dosen_papers_scholar_raw.csv` → Output: `dosen_papers_scholar.csv`

In [2]:
paper_pipeline.run_scholar_enrichment()

🔬 STEP 5: SCHOLAR ENRICHMENT (S2 → Google Scholar → Deep Scraping)
======================================================================
   📋 Loaded 6090 papers from dosen_papers_scholar.csv

[1/6090] & Praswati, An (2024)...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[2/6090] 2013 Curriculum: Assessment Of Minimum Competencies In Freedom Learnin...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[3/6090] 2018 5Th International Conference On Electrical Engineering, Computer ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[4/6090] 2020 The Third International Conference On Vocational Education And El...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[5/6090] 2021 Fourth International Conference On Vocational Education And Elect...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[6/6090] 2024 6Th International Workshop On Artificial Intelligence And Educati...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[7/6090] 3D Human Pose Estimation Using Blazepose And Direct Linear Transform (...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[8/6090] 7Th International Conference On Educational Technology Of Adi Buana...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[9/6090] A 2-Dof Robot Arm Simulation For Kinematics Learning...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[10/6090] A Case Study At A Civil Aviation School On Using Problem-Based Learnin...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[11/6090] A Cobit-Based Framework For Assessing The Maturity Level Of Sinau Digi...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[12/6090] A Cognitive Assessment Instrument For Hots Development In Technical Dr...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[13/6090] A Comparative Study Of Pca, Fft And Wavelet As Feature Extraction For ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[14/6090] A Comparative Study Of Supervised Feature Selection Methods For Predic...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[15/6090] A Comprehensive Research Of Supervised Learning Strategies Using Machi...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[16/6090] A Design Of Inventory Information System For Borrowing And Returning O...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[17/6090] A Desirable Online Digital Music Sales Design-A Systematic Literature ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[18/6090] A Development Of Web-Based Information System Of Monitoring And Evalua...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[19/6090] A Effort Of An Academic Supervision On Guidance And Counselling Teache...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[20/6090] A Engineering Of Information Technology Requirement Of Final Project Q...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[21/6090] A General Framework Of Covid-19 Model With Control Strategies: The App...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[22/6090] A Hybrid Clustering–Classification Framework For Smes Success Level Pr...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[23/6090] A Hybrid Intelligent System For Decision Making...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[24/6090] A Learning Trajectory For Developing Computational Thinking In Prospec...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[25/6090] A Lesson Learned From Pioneer Of Gastrodiplomacy: Strategies Of Utiliz...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[26/6090] A Longitudinal Evaluation Of Student Knowledges And Skills Development...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[27/6090] A Measurement Of Performance: Student Involvement In Organization And ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[28/6090] A New Adaptive Droop Control Strategy For Improved Power Sharing Accur...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[29/6090] A Novel Modified Tornado Optimizer With Coriolis Force Based On Levy F...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[30/6090] A Pemberdayaan Perajin Batik Sidomukti Melalui Teknologi Produksi Dan ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[31/6090] A Performance Comparison Of Lstm And Gru Architectures For Forecasting...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[32/6090] A Photographer Guided Framework For Web Image Falsification Detection ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[33/6090] A Pilates-Based Physiological Recovery Strategy To Enhance Post-Exerci...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[34/6090] A Preliminary Study And Validation Of Characters As The Basis For Merd...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[35/6090] A Project-Based Learning At University: Preparing Special Education Te...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[36/6090] A Proposal Of Inclusive Tourism Using A Yolo-Based Image-To-Audio Conv...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[37/6090] A Proposed Assessment Tool For Sharia-Compliant Equity Crowdfunding Pr...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[38/6090] A Quantitative Study On The Scientific Literacy Skills Of Prospective ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[39/6090] A Review On Automatic Speech Recognition: Indonesian Speech Recognitio...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[40/6090] A Special Service Of Guidance And Counseling Management To Reduce The ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[41/6090] A Study Of Fingerprint-Based Indoor Localization System Using Ieee 802...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[42/6090] A Study On Cloud-Based Dynamic Group Formation Problem...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[43/6090] A Systematic Literature Review Of Adaptive Coding Curriculum And Artif...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[44/6090] A Systematic Literature Review Of Digital Marketing Ethics Practices I...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[45/6090] A Systematic Literature Review Of Emotional Intelligence And It Invest...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[46/6090] A Systematic Literature Review Of Project-Based Learning Integrated Wi...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[47/6090] A Systematic Literature Review On Blockchain Technology In Software En...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[48/6090] A Systematic Literature Review On Chatbot Development For Whatsapp: Pr...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[49/6090] A Systematic Review Of Physical Artificial Intelligence (Physical Ai):...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[50/6090] A Systematic Review On Market Orientation And Marketing Performance In...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[51/6090] A Training On Designing 3D-Based On Instructional Media To Enhance Ele...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[52/6090] A Webometric Analysis On State Higher Education Institutions In Indone...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[53/6090] A" Splash" Of Taiwan Bubble Tea: Gastrodiplomacy, Nation Brand And A S...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[54/6090] A. Pendekatan Dan Jenis Penelitian...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[55/6090] Abridged Neat Key Instance: An Integrity Property For Digital Multimed...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[56/6090] Achievement Of Graduates On Skills That Have Been Given By Education U...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[57/6090] Acne Facial Skin Care With The Beauty Electrical Tool Through Problem ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[58/6090] Activity-Based Function Point Complexity Of Use Case Diagrams For Soft...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[59/6090] Actualization Of Principal Instructional Leadership In The Implementat...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[60/6090] Adapting Business Model With Covid-19 Pandemic Using Business Strategi...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[61/6090] Adapting The Academic Motivation Scale For Homeschool Students In Indo...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[62/6090] Adaptive Bitrate Streaming Untuk Peningkatan Kualitas Penerimaan Video...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[63/6090] Adaptive Smart Lighting Dengan Memanfaatkan Teknologi Berbasis Interne...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[64/6090] Adaptive Social Media Management For Higher Education Image Transforma...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[65/6090] Adaptive Traffic Light Control System Using Camera Sensor And Embedded...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[66/6090] Adiksimba Sebagai Metode Berpikir Logis Dalam Meningkatkan Kemampuan M...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[67/6090] Advancing Efficiency, Transparency, And Accuracy Of Digital Quality As...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[68/6090] Aero Pendulum, Pid, Tyreus-Luybe Desain Sistem Kontroler Pid Tyreus-Lu...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[69/6090] Agen Pembagi Zakat Berdasarkan Citra Pola Pakaian Menggunakan Metode K...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[70/6090] Agentic Artificial Intelligence In Business: A Systematic Literature R...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[71/6090] Agents Of Change In The Management Of Community Empowerment Through No...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[72/6090] Agile Development Of A Project Based Learning Management Application: ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[73/6090] Agustus. Pengembangan Media Pembelajaran Matematika Berbasis Ict Yang ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[74/6090] Ai Chatbot As A Prompt Generator: A Solution For Enhancing Digital Mar...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[75/6090] Ai-Based Business Model Analysis Of Education-Focused Beauty Salon Ent...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[76/6090] Al-Ulum...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[77/6090] Alat Pengukur Status Gizi Balita Berdasarkan Berat Dan Panjang Badan M...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[78/6090] Alat Prediksi Curah Hujan Dengan Menggunakan Weather Sensor Sebagai Pe...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[79/6090] Alat Ukur Panjang Dan Berat Badan Balita Untuk Menentukan Kategori Sta...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[80/6090] Algorithmic Advancements In Heuristic Search For Enhanced Sudoku Puzzl...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[81/6090] Algoritma Baru Pembentukan Kata Dasar Pada Proses Stemming Bahasa Indo...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[82/6090] Algoritma Dan Pemrograman Dengan Python Untuk Pemula...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[83/6090] Algoritma K-Nearest Neighbour Untuk Memprediksi Harga Jual Tanah...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[84/6090] Algoritma Madm Pada Sistem Pendukung Keputusan Untuk Peminjam Ruang Ra...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[85/6090] Algoritma Pendeteksi Marka Jalan Berbasis Pengolahan Citra Sebagai Pem...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[86/6090] Algoritma Stemming Nazief & Adriani Dengan Metode Cosine Similarity Un...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[87/6090] Allocation Priority Determination System For Provincial Bridge Mainten...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[88/6090] An Adaptive Power System Stabilizer Based On Focused Time Delay Neural...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[89/6090] An Analisis And Design Of Lecturer Portfolio Information System In Dep...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[90/6090] An Andragogy Perspective In Thoriqoh Qodiriyah Wanaqsyabandiyyah Activ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[91/6090] An Automated Essay Scoring Based On Neural Networks To Predict And Cla...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[92/6090] An Improved Simulated Annealing For The Capacitated Vehicle Routing Pr...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[93/6090] An Influence Of Problem-Based Learning Models Assisted By Media Traine...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[94/6090] An Innovative Solar Power Forecasting On Grid Using Feed Forward Neura...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[95/6090] An Intelligent Decision Support Based On A Subtractive Clustering And ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[96/6090] An Introductory Book For Coaching Athletes With A Disability...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[97/6090] An Investigation Of Fingerprint-Based Room Detection Method Using Ieee...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[98/6090] An Investigation Of Secondary Teachers’ Understanding And Belief On Ma...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[99/6090] An Iot-Based Smart Training Kit For Futsal Athlete Fitness Monitoring:...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[100/6090] Analisa Dan Desain Sistem Seleksi Calon Penerima Beasiswa...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[101/6090] Analisa Dan Perancangan Check-Ap: Aplikasi Pemeriksaan Kesehatan Anak ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[102/6090] Analisa Dan Perancangan Sistem Informasi Penggajian Karyawan Berbasis ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[103/6090] Analisa Dan Permodelan Proses Bisnis Pada Cv Tekad Jaya Mandiri Menggu...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[104/6090] Analisa Efek Kemiringan Pemasangan Terhadap Luaran Daya Rangkaian Pane...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[105/6090] Analisa Kesuksesan Sistem Informasi Akademik (Siakad) Di Perguruan Tin...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[106/6090] Analisa Kesuksesan Sistem Informasi Akademik Di Perguruan Tinggi Denga...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[107/6090] Analisa Kinerja Protokol Routing Delay Tolerant Network (Dtn) Untuk Tr...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[108/6090] Analisa Layanan Pada Aplikasi Kesehatan Dengan Framework Itil V3 Domai...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[109/6090] Analisa Learning Rate Dan Batch Size Pada Klasifikasi Covid Menggunaka...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[110/6090] Analisa Pemetaan Kriminalitas Kabupaten Bangkalan Menggunakan Metode K...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[111/6090] Analisa Pengaruh Routing Protokol Dan Mekanisme Keamanan Pada Kualitas...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[112/6090] Analisa Penggunaan Kapasitor Bank Terhadap Faktor Daya Pada Gedung Idb...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[113/6090] Analisa Penggunaan Kapasitor Bank Terhadap Faktor Daya Pada Gedung Idb...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[114/6090] Analisa Pengujian Gui Pada Website Online Course Ruangguru & Zenius De...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[115/6090] Analisa Perancangan Analisa Perancangan Sistem Informasi Berbasis Web ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[116/6090] Analisa Perhitungan Analitik Dan Data Eksperimen Parameter Gelombang P...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[117/6090] Analisa Perubahan Daya Aktif Generator Serta Efisiensi Mekanik Generat...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[118/6090] Analisa Proses Bisnis Pengadilan Agama Surabaya Menggunakan Metode Bus...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[119/6090] Analisa Tata Kelola Infrastruktur Teknologi Informasi Berdasarkan Cobi...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[120/6090] Analisa Tingkat Kematangan Sumber Daya Manusia Ti Menggunakan Cobit 4....
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[121/6090] Analisa Tingkat Penerimaan Dan Pengaruh Literasi Digital Terhadap Peng...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[122/6090] Analisia Dan Pemodelan Proses Bisnis Menggunakan Metode Business Proce...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[123/6090] Analisis Akurasi Metode Seleksi Fitur Gram-Schmidt Orthogonalization P...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[124/6090] Analisis Algoritma Klasifikasi Untuk Memprediksi Karakteristik Mahasis...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[125/6090] Analisis Algoritma Penjadwalan Priority Queueing (Pq) Terhadap Quality...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[126/6090] Analisis Arus Transien Transformator Saat Penyambungan Beban Di Batu N...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[127/6090] Analisis Audit Energi Listrik Pada Gedung Jurusan Teknik Elektro Unive...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[128/6090] Analisis Beban Kerja Kognitif Siswa Sekolah Menengah Pertama Pada Tuga...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[129/6090] Analisis Biaya Persediaan Dan Biaya Pengiriman Untuk Material Import D...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[130/6090] Analisis Bibliometrik Implementasi Kecerdasan Buatan Dalam Ketenagaker...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[131/6090] Analisis Chatbot Pendaftaran Mahasiswa Baru Menggunakan Algoritma Arti...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[132/6090] Analisis Dalam Mengelola Keuangan Berdasarkan Perspektif 2 Korintus 9:...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[133/6090] Analisis Dampak Integrasi Data Terhadap Kecepatan Pelayanan Publik Di ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[134/6090] Analisis Dampak Lalu Lintas Akibat Pembangunan Wisata Alam Desa Medowo...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[135/6090] Analisis Dampak Moneter, Kesiapan Teknologi, Dan Ancaman Keamanan Mata...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[136/6090] Analisis Dan Desain Sistem Aplikasi Penjadwalan Kuliah Pengganti (Resc...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[137/6090] Analisis Dan Desain Sistem Informasi Berbasis Website Gereja Katolik S...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[138/6090] Analisis Dan Desain Sistem Pendataan Kewirausahaan Mahasiswa...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[139/6090] Analisis Dan Efisiensi Kebutuhan Kapasitas Baterai 110 Volt Dc Gas Ins...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[140/6090] Analisis Dan Implementasi Honeypot Dalam Mendeteksi Serangan Distribut...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[141/6090] Analisis Dan Pengujian Dictionary Attack Terhadap Wpa3 Berbasis Script...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[142/6090] Analisis Dan Perancangan Sistem Informasi Layanan Kerusakan Mesin Edc ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[143/6090] Analisis Dan Perancangan Sistem Informasi Penjualan Dengan Metode Fast...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[144/6090] Analisis Dan Perancangan System Application Verification Questioner (S...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[145/6090] Analisis Dan Perancangan User Experience Aplikasi Sosial Media Family ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[146/6090] Analisis Dan Perbaikan User Interface (Ui) Untuk Meningkatkan User Exp...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[147/6090] Analisis Dan Rekonstruksi Desain Kegiatan Laboratorium (Dkl) Materi Sp...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[148/6090] Analisis Dan Simulasi Parameter Akustik Ruang Pada Gedung Kesenian Cak...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[149/6090] Analisis Dan Simulasi Sistem Kontrol Suhu Otomatis Berbasis Fuzzy Logi...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[150/6090] Analisis Desain Solar Tube Dengan Panel Surya Pada Rumah Tinggal...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[151/6090] Analisis Efektivitas Native Advertising Sebagai Media Periklanan Berba...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[152/6090] Analisis Efektivitas Penggunaan Model Pembelajaran Hybrid Learning Di ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[153/6090] Analisis Efisiensi Aplikasi Administrasi “Jembul Smart Village” Dalam ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[154/6090] Analisis Faktor Kesuksesan Aplikasi Danareksa Online Next Generation D...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).

[155/6090] Analisis Faktor Motivasi Antara Mahasiswa Bidikmisi Dan Non Bidikmisi ...
   ⏭️ [Resume] Dilewati (Sudah dievaluasi).


KeyboardInterrupt:

In [1]:
import sys
import pandas as pd
from pathlib import Path

# Kunci folder Tugas_Akhir agar Python bisa membaca 'src.etl'
root_path = r"C:\Users\rizky_11yf1be\Desktop\Tugas_Akhir"
if root_path not in sys.path:
    sys.path.insert(0, root_path)

print("🚀 CELL 1: MENCARI PAPER SPESIFIK DARI DATA MENTAH SCHOLAR")

raw_csv_path = Path(root_path) / "notebooks" / "scraping" / "file_tabulars" / "dosen_papers_scholar_raw.csv"

if not raw_csv_path.exists():
    print(f"❌ File tidak ditemukan: {raw_csv_path}")
else:
    df_all_raw = pd.read_csv(raw_csv_path, dtype=str).fillna("")
    
    # 🎯 GANTI JUDUL PAPER YANG INGIN ANDA DEBUG DI SINI
    # (Bisa ketik sebagian judul saja, misalnya: "Rekomendasi Film Berbasis Web")
    target_title = "Pelatihan Aplikasi Komputer untuk Penulisan Ilmiah di SMPN 1 Pagerwojo Tulungagung Jawa Timur: Computer Application Training for Scientific Writing at SMPN 1 Pagerwojo"
    
    # Mode Pencarian Cerdas (mengabaikan huruf besar/kecil)
    df_sample = df_all_raw[df_all_raw['Title'].str.contains(target_title, case=False, regex=False, na=False)].copy()
    
    if df_sample.empty:
         print(f"⚠️ Paper yang mengandung kata '{target_title}' TIDAK DITEMUKAN di raw CSV!")
    else:
        # Ambil baris pertama saja jika ada lebih dari 1 temuan
        df_sample = df_sample.head(1).copy()
        print(f"✅ Ditemukan 1 paper yang cocok!")
        
        # Pindahkan kolom raw ke kolom standar ETL
        if 'Authors_raw' in df_sample.columns:
            df_sample['Authors'] = df_sample['Authors_raw']
        elif 'Authors' not in df_sample.columns:
            df_sample['Authors'] = ""
            
        # Kosongkan Kolom yang akan Dites oleh Mesin Pabrik
        df_sample['Author IDs'] = ""
        df_sample['Abstract'] = ""
        df_sample['Keywords'] = ""
        df_sample['DOI'] = ""
        df_sample['TLDR'] = ""
        df_sample['enriched'] = "False" 

        print("\n👉 Wujud Data Mentah Sebelum ETL (Singkatan Asli Scholar):")
        display(df_sample[['Title', 'Authors', 'scholar_id', 'dosen']])

🚀 CELL 1: MENCARI PAPER SPESIFIK DARI DATA MENTAH SCHOLAR
✅ Ditemukan 1 paper yang cocok!

👉 Wujud Data Mentah Sebelum ETL (Singkatan Asli Scholar):

,Title,Authors,scholar_id,dosen
2,Pelatihan Aplikasi Komputer untuk Penulisan Il...,"Y Yamasari, A Qoiriah, RE Putra, A Prihanto, I...",WdhKN0sAAAAJ,"Aditya Prapanca, S.T., M.Kom."

In [2]:
# Panggil mesin pabrik asli dari 'src/etl'
from src.etl.transform.cleaner import clean_papers_batch
from src.etl.transform.enricher import enrich_paper_batch, generate_local_tldr
import textwrap
import time

print("🚀 CELL 2: MENEMBAKKAN MESIN PRODUKSI AIRFLOW KE DATA MENTAH")

if 'df_sample' not in locals() or df_sample.empty:
    print("⚠️ Harap jalankan Cell 1 terlebih dahulu dan pastikan judul paper ditemukan!")
else:
    # Catat waktu mulai keseluruhan
    t_start_total = time.time()
    
    # --- 1. TAHAP CLEANING & AUTHOR MATCHING ---
    print("\n🧹 1. Memulai Cleaning & Matching Author...")
    df_cleaned = clean_papers_batch(df_sample.copy().reset_index(drop=True))
    
    # --- 2. TAHAP ENRICHMENT DENGAN AKSES PROXY BERBAYAR ---
    print("📡 2. Memulai Enrichment Cerdas (S2 & OpenAlex APIs + Groq TLDR)...")
    df_enriched = enrich_paper_batch(
        df_cleaned.copy(), 
        batch_size=1, 
        start_idx=0,
        allow_paid_proxy=True 
    )
    
    t_end_total = time.time()
    total_duration = t_end_total - t_start_total
    
    # --- 3. TAMPILKAN HASIL EKSTRAKSI LENGKAP SECARA VERTIKAL ---
    print("\n" + "="*100)
    print("🔍 HASIL EKSTRAKSI LENGKAP (ALL COLUMNS)")
    print("="*100)
    
    final_columns = [
        'Title', 'Authors', 'Author IDs', 'Journal', 
        'Document Type', 'Abstract', 'Keywords', 'DOI', 'TLDR'
    ]
    
    abstract_text = ""
    title_text = ""
    
    for idx, row in df_enriched.iterrows():
        title_text = str(row.get('Title', ''))
        abstract_text = str(row.get('Abstract', ''))
        
        for col in final_columns:
            val = str(row.get(col, ''))
            if not val or val.lower() == 'nan': val = "(Kosong)"
                
            if col in ['Title', 'Abstract', 'TLDR'] and val != "(Kosong)":
                val = "\n\t" + textwrap.fill(val, width=90).replace("\n", "\n\t")
            elif col == 'Keywords' and val != "(Kosong)":
                val = textwrap.fill(val, width=90).replace("\n", "\n\t\t")
                
            print(f"{col:<15}\t{val}")
        print("="*100)
        
    # --- 4. BENCHMARK WAKTU & KECEPATAN ---
    print("\n⏱️ BENCHMARK WAKTU EKSEKUSI")
    print("-" * 50)
    
    # Kita panggil ulang API Groq secara terpisah khusus untuk menghitung latensi asli LLM
    tldr_duration = 0
    if abstract_text and abstract_text.lower() != 'nan':
        print("(Menghitung latensi murni TLDR Generation API...)")
        t_tldr_start = time.time()
        _ = generate_local_tldr(title_text, abstract_text)
        tldr_duration = time.time() - t_tldr_start
    
    scraping_duration = total_duration - tldr_duration
    if scraping_duration < 0: scraping_duration = total_duration # Fallback safety
    
    print(f"Tugas                  | Waktu Ditempuh")
    print(f"-----------------------|----------------")
    print(f"1. Scraping & Metadata | ~{scraping_duration:.2f} detik")
    print(f"2. Generate TL;DR (AI) |  {tldr_duration:.2f} detik")
    print(f"-----------------------|----------------")
    print(f"Total Pipeline         |  {total_duration:.2f} detik")
    print("=" * 50)

✅ Config: Loaded Credentials (Supabase: https://wfjzdhaaldwyiajbyzln.supabase.co)
🚀 CELL 2: MENEMBAKKAN MESIN PRODUKSI AIRFLOW KE DATA MENTAH

🧹 1. Memulai Cleaning & Matching Author...
🧹 Starting data cleaning for 1 records...
👩‍🏫 Normalizing author names & enriching Author IDs...
✅ Lecturer DB loaded: 129 names, 228 IDs
   ✅ Normalized 1/1 author names to canonical lecturer names
✅ Data cleaning complete. No more messy whitespaces/newlines.
📡 2. Memulai Enrichment Cerdas (S2 & OpenAlex APIs + Groq TLDR)...

🔧 ENRICH: Processing batch of 1 papers (idx 0-1)
============================================================

[1/1] Pelatihan Aplikasi Komputer untuk Penulisan Ilmiah di SMPN 1...
   [Phase 1] Semantic Scholar...
      ⚠️ [S2] No strict match. Best: 'Pelatihan Aplikasi Komputer untuk Penulisan Ilmiah...'
      -> MISS: Not found in S2
   [Phase 2] OpenAlex...
      -> MISS: Not found in OpenAlex
   [Phase 2.5] BrightData Scholar (PAID Proxy)...
✅ Config: Loaded Dual-Proxy Credentials (Unlocker + SERP)
✅ Config: Loaded Credentials (Supabase: https://wfjzdhaaldwyiajbyzln.supabase.co)
✅ Config: Loaded Credentials (Supabase: https://wfjzdhaaldwyiajbyzln.supabase.co)
   [BrightData SERP API] Searching Scholar for: Pelatihan Aplikasi Komputer untuk Penulisan Ilmiah...
      🔄 Retry 2/2...
      ⚠️ API Error or No Results. Falling back to HTML Scraping (Unlocker)...
   [BrightData] Searching Scholar (HTML) for: Pelatihan Aplikasi Komputer untuk Penulisan Ilmiah...
      ✅ Found HTML Search Result: Pelatihan Aplikasi Komputer untuk Penuli...
      📄 PDF Link: https://journal.umpr.ac.id/index.php/pengabdianmu/...
      -> Scholar-Web (Proxy): https://journal.umpr.ac.id/index.php/pen...
      [Publisher] ✅ Keywords dari HTML: Computer Application Professionalism Scientific writing...
      [Publisher] ✅ Doc Type dari meta tags: Articles
      -> ✓ BD fallback performed
   [Phase 3] Local SciTLDR (Qwen2.5-0.5B PEFT)...
      ✅ Groq API Client initialized successfully.
      ✨ Generated: Teacher professionalism development in SMP Negeri 1 Pagerwoj...
   [Phase 4] Author Resolution & Proxy Fallback...
      ✅ Resolved: Aditya Prapanca; Yuni Yamasari; Anita Qoiriah; Ricky Eka Putra; Agus Prihanto; I Made Suartana | IDs: WdhKN0sAAAAJ; hn5jrnAAAAAJ; N6RJilIAAAAJ; cPj-iOIAAAAJ; -_VNTSIAAAAJ; RvG7jG4AAAAJ
   ✅ [1/1] ETA: 0.0 min

============================================================
ENRICHMENT BATCH DONE - 1 papers processed
   S2 hits        : 0/1
   OA hits        : 0/1
   Abstract       : 1/1
   Keywords       : 1/1
   DOI            : 1/1
   TLDR (total)   : 1/1
   TLDR (local)   : 1/1
   Authors resolved: 1/1
============================================================

====================================================================================================
🔍 HASIL EKSTRAKSI LENGKAP (ALL COLUMNS)
====================================================================================================
Title
	Pelatihan Aplikasi Komputer untuk Penulisan Ilmiah di SMPN 1 Pagerwojo Tulungagung Jawa
	Timur: Computer Application Training for Scientific Writing at SMPN 1 Pagerwojo …
Authors        	Aditya Prapanca; Yuni Yamasari; Anita Qoiriah; Ricky Eka Putra; Agus Prihanto; I Made Suartana
Author IDs     	WdhKN0sAAAAJ; hn5jrnAAAAAJ; N6RJilIAAAAJ; cPj-iOIAAAAJ; -_VNTSIAAAAJ; RvG7jG4AAAAJ
Journal        	PengabdianMu: Jurnal Ilmiah Pengabdian kepada Masyarakat 10 (8), 1936-1943, 2025
Document Type  	Artikel
Abstract
	Teacher professionalism development is one of the strategic steps in improving the quality
	of education at SMP Negeri 1 Pagerwojo, Tulungagung, East Java. However, limited access to
	training and a lack of utilization of technology are significant obstacles for teachers,
	especially in the field of scientific writing. Scientific writing skills are essential in
	improving teaching skills, developing learning materials, and contributing to educational
	literature. To solve this problem, this community service activity aims to enhance
	teachers' skills in scientific writing through training in the use of applications. The
	training utilizes key features, such as reference management, automatic citation settings,
	and scientific document management. The training method includes the application
	installation stage, direct training, and analysis of results through measuring participant
	responses using a Likert scale. The study showed that the training improved teachers'
	understanding and skills in utilizing technology to support scientific writing. Most
	participants responded positively to the training, with a percentage of 77.55%. These
	results indicate that similar training needs to be further developed to support teacher
	professionalism, especially in areas with limited access to training.
Keywords       	computer application professionalism scientific writing
DOI            	10.33084/pengabdianmu.v10i8.9435
TLDR
	Teacher professionalism development in SMP Negeri 1 Pagerwojo, Tulungagung, East Java, is
	hindered by limited training access and technology utilization. Experiments were conducted
	using a Likert scale to measure participant responses, achieving a positive response
	percentage of 77.55%.
====================================================================================================

⏱️ BENCHMARK WAKTU EKSEKUSI
--------------------------------------------------
(Menghitung latensi murni TLDR Generation API...)
Tugas                  | Waktu Ditempuh
-----------------------|----------------
1. Scraping & Metadata | ~25.70 detik
2. Generate TL;DR (AI) |  3.30 detik
-----------------------|----------------
Total Pipeline         |  29.00 detik
==================================================

In [3]:
import time
from groq import Groq

# Configuration
GROQ_API_KEY = "***REMOVED***"
client = Groq(api_key=GROQ_API_KEY)

abstract = """	Kekerasan seksual di lingkungan perguruan tinggi menjadi perhatian utama Kemendikbud
	Ristek. Tercatat sebanyak 15% dari total kasus kekerasan seksual terjadi di lingkungan
	perguruan tinggi. Persentase ini didapat dari data survei Direktorat Jenderal Pendidikan
	Tinggi, Riset, dan Teknologi di tahun 2020. Untuk mengatasi permasalahan ini, Kemendikbud
	Ristek menerbitkan Permendikbud Ristek Nomor 30 Tahun 2021 yang mengatur pencegahan dan
	penanganan kekerasan seksual di perguruan tinggi. Salah satu upaya mendukung Permendikbud
	Ristek Nomor 30 Tahun 2021 dibentuklah Satgas PPKS di Universitas Negeri Surabaya (UNESA)
	yang menyediakan layanan pengaduan melalui melalui media whatsapp, telepon, dan pengisian
	form digital. Penelitian ini bertujuan mengembangkan bot telegram dengan metode komunikasi
	webhook dan integrasi dengan google spreadsheet sebagai sistem layanan pengaduan Satgas
	PPKS dengan memberikan kemudahan proses pelaporan, cek status laporan hingga penjadwalan
	pertemuan investigasi jika diperlukan. Hasil penelitian menunjukkan bahwa bot telegram ini
	mampu memberikan respons secara realtime tanpa bug dalam sistem dan kecepatan respons yang
	termasuk dalam kategori cepat dengan rentang waktu berkisar antara 1050 ms hingga 1680 ms."""

# -------------------------------------------------------------
# 1. PROMPT UNTUK TLDR (ANTI BACOT & SUPER KETAT)
# -------------------------------------------------------------
system_prompt_tldr = """You are an AI assistant specializing in strict academic data extraction.
Your Task: Read the following journal abstract and summarize it into EXACTLY 2 SENTENCES in ENGLISH that are very dense and specific.

ONTOLOGY SCHEMA RULES:
[Problem], [Task], [Field], [Method], [Model], [Innovation], [Dataset], [Tool], [Metric].

STRUCTURE (MANDATORY):
Sentence 1: Background & Approach (You MUST include Problem/Task, Field, and Method).
Sentence 2: Experiments & Results (You MUST explicitly write out the Metric, Tool, and Dataset used).

EXAMPLE 1 (Algorithm Research):
Abstract: "Penelitian mendeteksi hoaks pada Twitter menggunakan algoritma BERT. Kami menggunakan dataset ID-Hoax dan mencapai akurasi 95%."
Output: This research addresses hoof detection within the Twitter social media domain using the BERT algorithm. Experiments were conducted on the ID-Hoax dataset and achieved an accuracy of 95%.

EXAMPLE 2 (System/App Development):
Abstract: "Penelitian ini mengembangkan bot telegram di UNESA. Hasil menunjukkan bot mampu memberi respons realtime tanpa bug dengan kecepatan 1050 ms hingga 1680 ms."
Output: This study develops a Telegram bot system with webhook integration for sexual violence reporting services at Universitas Negeri Surabaya. Performance measurement results indicated a fast real-time response capability ranging from 1050 ms to 1680 ms without system bugs.

CRITICAL RULES:
- You are FORBIDDEN from outputting only 1 sentence. YOU MUST OUTPUT EXACTLY 2 SENTENCES.
- If there are numbers, percentages, or ms (milliseconds) in the abstract, you MUST include them in Sentence 2 as the [Metric].
- NO pronouns like "this method".
- THE OUTPUT MUST BE IN ENGLISH.
- DO NOT output any introductory text, conversational fillers, or phrases like 'Here is the summary'. START IMMEDIATELY with the first sentence."""

# -------------------------------------------------------------
# 2. PROMPT UNTUK KEYWORDS
# -------------------------------------------------------------
system_prompt_keyword = """You are an AI assistant specializing in academic data extraction.
Your Task: Read the following journal abstract and extract EXACTLY 4 to 5 highly relevant academic keywords.

STRICT RULES:
- Output ONLY the keywords separated by commas.
- Do NOT output any introductory or conversational text like "Here are the keywords".
- Do NOT output bullet points or numbers.
- The keywords MUST be in the EXACT same language as the abstract."""

# HANYA 2 MODEL TERPILIH UNTUK BENCHMARK FINAL
models_to_test = [
    "llama-3.1-8b-instant",
    "meta-llama/llama-4-scout-17b-16e-instruct"
]

print("="*80)
print("🚀 BENCHMARKING FINAL (Llama 8B vs Llama 4 Scout 17B)")
print("="*80)

for model_name in models_to_test:
    total_start_time = time.time()
    try:
        # --- PROSES 1: GENERATE TLDR ---
        tldr_completion = client.chat.completions.create(
            model=model_name,
            messages=[
                {"role": "system", "content": system_prompt_tldr},
                {"role": "user", "content": f"ORIGINAL ABSTRACT:\n{abstract}\n\nOUTPUT 2-SENTENCE TL;DR IN ENGLISH:"}
            ],
            temperature=0.0, 
            max_tokens=256,
            stream=False
        )
        res_tldr = tldr_completion.choices[0].message.content.strip()
        tldr_tokens = tldr_completion.usage.total_tokens
        
        # Jeda 2 detik antar panggilan API untuk aman dari limit
        time.sleep(2)
        
        # --- PROSES 2: GENERATE KEYWORDS ---
        kw_completion = client.chat.completions.create(
            model=model_name,
            messages=[
                {"role": "system", "content": system_prompt_keyword},
                {"role": "user", "content": f"ABSTRACT:\n{abstract}\n\nKEYWORDS:"}
            ],
            temperature=0.0,
            max_tokens=64,
            stream=False
        )
        res_kw = kw_completion.choices[0].message.content.strip()
        kw_tokens = kw_completion.usage.total_tokens
        
        # --- KALKULASI TOTAL ---
        total_duration = time.time() - total_start_time
        grand_total_tokens = tldr_tokens + kw_tokens
        
        print(f"\n🧠 Model : [{model_name}]")
        print(f"⏱️ Waktu : {total_duration:.2f} detik (TLDR + Keyword)")
        print(f"🪙 Token : {tldr_tokens} (TLDR) + {kw_tokens} (Keywords) = Total {grand_total_tokens} Token")
        print("-" * 50)
        print(f"📝 Hasil TLDR:\n{res_tldr}")
        print("\n🔑 Hasil Keywords:\n" + res_kw)
        print("="*80)
        
        # Jeda 3 detik untuk maju ke model selanjutnya
        time.sleep(3)
        
    except Exception as e:
        print(f"\n🧠 Model : [{model_name}]")
        print(f"⚠️ Error : {e}")
        print("="*80)

================================================================================
🚀 BENCHMARKING FINAL (Llama 8B vs Llama 4 Scout 17B)
================================================================================

🧠 Model : [llama-3.1-8b-instant]
⏱️ Waktu : 3.75 detik (TLDR + Keyword)
🪙 Token : 930 (TLDR) + 535 (Keywords) = Total 1465 Token
--------------------------------------------------
📝 Hasil TLDR:
Sexual violence in higher education institutions has become a primary concern for the Ministry of Education, Culture, Research, and Technology. Experiments were conducted on a Telegram bot system with webhook integration for sexual violence reporting services at Universitas Negeri Surabaya, achieving a fast real-time response capability ranging from 1050 ms to 1680 ms without system bugs.

🔑 Hasil Keywords:
Kekerasan seksual, Perguruan tinggi, Pencegahan, Penanganan, Sistem layanan pengaduan
================================================================================

🧠 Model : [meta-llama/llama-4-scout-17b-16e-instruct]
⏱️ Waktu : 2.57 detik (TLDR + Keyword)
🪙 Token : 766 (TLDR) + 399 (Keywords) = Total 1165 Token
--------------------------------------------------
📝 Hasil TLDR:
The problem of sexual violence in higher education institutions is addressed through the development of a Telegram bot system with webhook integration for reporting services at Universitas Negeri Surabaya. Performance measurement results indicated a fast real-time response capability ranging from 1050 ms to 1680 ms without system bugs, achieved using a webhook communication method and Google Spreadsheet integration.

🔑 Hasil Keywords:
Kekerasan Seksual, Perguruan Tinggi, Satgas PPKS, Bot Telegram, Webhook
================================================================================

In [14]:
import json
import time
import requests
from groq import Groq

# Configuration
GROQ_API_KEY = "***REMOVED***"
client = Groq(api_key=GROQ_API_KEY)

print("="*100)
print("🤖 MEMULAI AGEN AI (TOOL USE) MENCARI PAPER...")
print("="*100)

# ==========================================
# 1. DEFINISIKAN ALAT (TOOL) DI DUNIA NYATA
# ==========================================
def search_semantic_scholar_by_title(title: str) -> str:
    """Fungsi Python Asli yang akan dijalankan otmatis oleh Groq AI"""
    print(f"   [🛠️ AI ACTION]: Menggunakan mesin pencari jurnal untuk mencari: '{title}'...")
    url = f"https://api.semanticscholar.org/graph/v1/paper/search?query={title}&limit=1&fields=title,authors,venue,publicationTypes,abstract,externalIds"
    try:
        response = requests.get(url, timeout=10)
        data = response.json()
        if data.get("data"):
            # Karena ini simulasi, kita kembalikan JSON mentah agar AI yang membacanya
            return json.dumps(data["data"][0])
        return "Paper tidak ditemukan di Semantic Scholar."
    except Exception as e:
        return f"Error jaringan saat mencari paper: {e}"

# ==========================================
# 2. DAFTARKAN ALAT TERSEBUT KE DALAM OTAK AI (GROQ)
# ==========================================
# Ini seperti memberi "Buku Petunjuk" ke LLM
tools = [
    {
        "type": "function",
        "function": {
            "name": "search_semantic_scholar_by_title",
            "description": "Cari data jurnal akademik asli di internet berdasarkan judul aslinya. Me-return Abstrak, Penulis, DOI, dan Jurnal tempatnya diterbitkan.",
            "parameters": {
                "type": "object",
                "properties": {
                    "title": {
                        "type": "string",
                        "description": "Judul spesifik dari paper/jurnal yang ingin dicari.",
                    }
                },
                "required": ["title"],
            },
        },
    }
]

# ==========================================
# 3. PROSES AGEN AI (TOOL-USE LOOP)
# ==========================================
SYSTEM_PROMPT = """You are an autonomous Academic Data Assistant. 
You are given a paper title by the user. 
STEPS:
1. Use your tools to search the internet for the exact abstract and metadata of the paper.
2. After receiving data from the tools, construct a COMPLETE AND EXACT formatted string block with 9 sections just like the user's ETL dashboard layout (Title, Authors, Author IDs, Journal, Document Type, Abstract, Keywords, DOI, TLDR).
3. The TLDR must be exactly 2 sentences explicitly covering the academic ontology (Problem, Task, Field, Method, Model, Dataset, Metric).
4. The Keywords must be 4-5 words separated by commas.
5. If the Author ID is missing, write 'None'.
6. Do NOT write any conversational prefix or suffix. Just return the extraction block with the '=' borders."""

# Pertanyaan pengguna
user_query = "Tolong cari dan formatkan paper ini secara lengkap: 'Applying Data Mining For Anomalies Detection On The Academic Performance Of Student'"

messages = [
    {"role": "system", "content": SYSTEM_PROMPT},
    {"role": "user", "content": user_query}
]

# Tahap 1: Tanya Llama mau melakukan apa
print("   [🧠 AI THINKING]: Memikirkan langkah untuk memecahkan permintaan User...")
response = client.chat.completions.create(
    model="llama-3.3-70b-versatile", # 70B sangat cerdas dalam Function Calling
    messages=messages,
    tools=tools,
    tool_choice="auto",
    max_tokens=2048
)

response_message = response.choices[0].message
tool_calls = response_message.tool_calls

# Tahap 2: Jika AI memutuskan pakai alat (Tools), maka eksekusi
if tool_calls:
    # Catat histori percakapan
    messages.append(response_message)
    
    for tool_call in tool_calls:
        function_name = tool_call.function.name
        function_args = json.loads(tool_call.function.arguments)
        
        # Panggil fungsi aslinya jika AI menyuruh memanggil nama tersebut
        if function_name == "search_semantic_scholar_by_title":
            function_response = search_semantic_scholar_by_title(
                title=function_args.get("title")
            )
            
            # Tahap 3: Kirim data asli internet kembali ke otak AI
            messages.append(
                {
                    "tool_call_id": tool_call.id,
                    "role": "tool",
                    "name": function_name,
                    "content": function_response,
                }
            )

    # Tahap 4: AI membaca data asli, lalu memformat ulang jadi Laporan Final
    print("   [🧠 AI THINKING]: Menemukan data! Sedang membaca abstrak dan merajut TLDR 2-Kalimat Ontologi...")
    second_response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=messages
    )
    
    final_output = second_response.choices[0].message.content
    print("\n" + final_output)
else:
    # Jika sekiranya AI bisa jawab langsung tanpa butuh ambil data internet
    print("\n" + response_message.content)

====================================================================================================
🤖 MEMULAI AGEN AI (TOOL USE) MENCARI PAPER...
====================================================================================================
   [🧠 AI THINKING]: Memikirkan langkah untuk memecahkan permintaan User...
   [🛠️ AI ACTION]: Menggunakan mesin pencari jurnal untuk mencari: 'Applying Data Mining For Anomalies Detection On The Academic Performance Of Student'...
   [🧠 AI THINKING]: Menemukan data! Sedang membaca abstrak dan merajut TLDR 2-Kalimat Ontologi...

=======================================
Title=Applying Data Mining For Anomalies Detection On The Academic Performance Of Student
Authors=None
Author IDs=None
Journal=None
Document Type=None
Abstract=None
Keywords=Data Mining, Anomalies Detection, Academic Performance
DOI=None
TLDR=This study applies data mining techniques to detect anomalies in student academic performance, utilizing a dataset of student grades and demographic information to identify patterns and trends. The approach combines clustering and classification methods to pinpoint underperforming students and provide insights for targeted interventions, ultimately aiming to improve student outcomes in the field of education.
=======================================

In [ ]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel

# Quantization config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)

# Load base model
base_model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen2.5-0.5B-Instruct",
    quantization_config=bnb_config,
    device_map="auto",
)

# Load adapter
model = PeftModel.from_pretrained(
    base_model,
    "tcy93/scitldr-qwen2.5-0.5b-summarizer"
)
model.eval()

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-0.5B-Instruct")

def summarize_expert_en(abstract: str) -> str:
    system_prompt = """You are an AI assistant specializing in academic data extraction.
Your Task: Read the following journal abstract and summarize it into EXACTLY 2 SENTENCES in ENGLISH that are very dense and specific.

ONTOLOGY SCHEMA RULES:
[Problem], [Task], [Field], [Method], [Model], [Innovation], [Dataset], [Tool], [Metric].

STRUCTURE:
Sentence 1: Background & Approach (Problem/Task, Field, Method).
Sentence 2: Experiments & Results (Dataset, Tool, Metric).

EXAMPLE:
Abstract: "Penelitian ini bertujuan mendeteksi hoaks pada Twitter menggunakan algoritma BERT. Kami menggunakan dataset ID-Hoax dan mencapai akurasi 95%."
Output: This research addresses hoax detection within the Twitter social media domain using the BERT algorithm. Experiments were conducted on the ID-Hoax dataset and achieved an accuracy of 95%.

STRICT RULES:
- NO pronouns like "this method".
- THE OUTPUT MUST BE IN ENGLISH.
- DO NOT explain what is missing."""

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": f"ORIGINAL ABSTRACT:\n{abstract}\n\nOUTPUT 2-SENTENCE TL;DR IN ENGLISH:"},
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    inputs = tokenizer(text, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=200,
            do_sample=True,
            temperature=0.2,
            top_p=0.9,
            repetition_penalty=1.2
        )

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True
    )
    return response.strip()

# Testing with English output
abstract_input = "Perkembangan industri hiburan digital yang pesat menuntut adanya sistem yang dapat membantu pengguna menemukan konten yang yang relevan secara cepat dan akurat. Fokus utama pengembangan ini adalah mengatasi dua permasalahan utama dalam Collaborative Filtering, yaitu data spartsity dan cold start problem. Penelitian ini menggunakan pendekatan kuantitaif dengan metode eksperimen dan dilakukan evaluasi terhadap fungsionalitas performa dan akurasi sistem. Selain itu hasil uji pengguna menunjukkan bahwa sistem mudah digunakan, cepat dalam merespon, serta mampu memberikan rekomendasi yang relevan."
print(summarize_expert_en(abstract_input))

2026-03-26 22:35:25,730 - INFO - Loading base model...
2026-03-26 22:35:27,876 - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-26 22:35:28,163 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-03-26 22:35:28,552 - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-26 22:35:28,598 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

2026-03-26 22:36:17,959 - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-26 22:36:18,247 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/generation_config.json "HTTP/1.1 200 OK"
2026-03-26 22:36:18,273 - INFO - Loading LoRA adapter...
2026-03-26 22:36:18,591 - INFO - HTTP Request: HEAD https://huggingface.co/tcy93/scitldr-qwen2.5-0.5b-summarizer/resolve/main/adapter_config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-26 22:36:18,855 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/tcy93/scitldr-qwen2.5-0.5b-summarizer/d0c4f117edddbfddbebeba7a21b549055baba589/adapter_config.json "HTTP/1.1 200 OK"
2026-03-26 22:36:19,170 - INFO - HTTP Request: HEAD https://huggingface.co/tcy93/scitldr-qwen2.5-0.5b-summarizer/resolve/main/adapter_config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-26 22:36:19,212 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/tcy93/scitldr-qwen2.5-0.5b-summarizer/d0c4f117edddbfddbebeba7a21b549055baba589/adapter_config.json "HTTP/1.1 200 OK"
2026-03-26 22:36:19,677 - INFO - HTTP Request: HEAD https://huggingface.co/tcy93/scitldr-qwen2.5-0.5b-summarizer/resolve/main/adapter_model.safetensors "HTTP/1.1 302 Found"
2026-03-26 22:36:19,957 - INFO - HTTP Request: HEAD https://huggingface.co/tcy93/scitldr-qwen2.5-0.5b-summarizer/resolve/main/adapter_model.safetensors "HTTP/1.1 302 Found"
2026-03-26 22:36:20,045 - INFO - Loading tokenizer...
2026-03-26 22:36:20,311 - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-26 22:36:20,334 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/config.json "HTTP/1.1 200 OK"
2026-03-26 22:36:20,735 - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-26 22:36:21,050 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2.5-0.5B-Instruct/7ae557604adf67be50417f59c2c2f167def9a775/tokenizer_config.json "HTTP/1.1 200 OK"
2026-03-26 22:36:21,377 - INFO - HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-03-26 22:36:21,666 - INFO - HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-26 22:36:23,161 - INFO - HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2.5-0.5B-Instruct "HTTP/1.1 200 OK"
2026-03-26 22:36:23,173 - INFO - Model ready.
2026-03-26 22:36:23,230 - INFO - Input token count: 314
The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

============================================================
TEST 1: Abstract Bahasa Indonesia
============================================================

2026-03-26 22:37:42,740 - INFO - Raw output: This work aims to address two main problems with collaborative filtering algorithms by using a new approach that can improve their performance.
2026-03-26 22:37:42,749 - INFO - Input token count: 222

Output:
This work aims to address two main problems with collaborative filtering algorithms by using a new approach that can improve their performance.

============================================================
TEST 2: Abstract Bahasa Inggris
============================================================

2026-03-26 22:38:26,340 - INFO - Raw output: Title Scaffolds Improve Summarization Performance
2026-03-26 22:38:26,350 - INFO - Input token count: 234

Output:
Title Scaffolds Improve Summarization Performance

============================================================
TEST 3: Abstract Campur Indo-Inggris
============================================================

2026-03-26 22:39:45,604 - INFO - Raw output: We propose a new model for Knowledge Graph Completion using Graph Neural Networks with state-of-the-art performance on Facebook Knowledge Base Dataset.
2026-03-26 22:39:45,608 - INFO - Processing [1/3] paper_id: paper_001

Output:
We propose a new model for Knowledge Graph Completion using Graph Neural Networks with state-of-the-art performance on Facebook Knowledge Base Dataset.

============================================================
TEST 4: Batch Processing
============================================================

2026-03-26 22:43:18,095 - INFO - Batch selesai: 3/3 berhasil.

[paper_001] Sistem Rekomendasi Berbasis Collaborative Filtering
  Status : success
  TLDR   : This work aims to address two main problems with collaborative filtering algorithms by using a new approach that can improve their performance.

[paper_002] Scientific Summarization with BART
  Status : success
  TLDR   : Title Scaffolds Improve Summarization Performance

[paper_003] GNN for Knowledge Graph Completion
  Status : success
  TLDR   : We propose a new model for Knowledge Graph Completion using Graph Neural Networks with state-of-the-art performance on Facebook Knowledge Base Dataset.

Hasil disimpan ke: tldr_results.json

In [ ]:
# ============================================================
# TLDR GENERATOR — Ontology-Aware (Revised)
# Model: tcy93/scitldr-qwen2.5-0.5b-summarizer
# Author: revised from original setup
# ============================================================

import torch
import json
import logging
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel
from typing import Optional

# Setup logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)


# ============================================================
# 1. MODEL SETUP
# ============================================================

# Quantization config — hemat VRAM, cukup untuk inference
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)

logger.info("Loading base model...")
base_model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen2.5-0.5B-Instruct",
    quantization_config=bnb_config,
    device_map="auto",
)

logger.info("Loading LoRA adapter...")
model = PeftModel.from_pretrained(
    base_model,
    "tcy93/scitldr-qwen2.5-0.5b-summarizer"
)
model.eval()

logger.info("Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-0.5B-Instruct")

logger.info("Model ready.")


# ============================================================
# 2. SYSTEM PROMPT — Cleaned, No Ineffective Schema Tags
# ============================================================

SYSTEM_PROMPT = """You are an academic paper summarizer.
Read the abstract below and generate exactly 2 sentences in ENGLISH:

- Sentence 1: State the research problem, task/domain, and method used.
- Sentence 2: State the key results, and mention dataset or metric ONLY IF explicitly stated in the abstract.

Rules:
- Output must be in English regardless of abstract language (Indonesian, English, or mixed).
- Do NOT invent datasets, metrics, or methods not mentioned in the abstract.
- If dataset or metric is not mentioned, omit it — do not fabricate.
- Be specific and dense, avoid generic phrases like "this study shows".
- No pronouns like "this method" or "the proposed system"."""


# ============================================================
# 3. VALIDATION
# ============================================================

def validate_tldr(tldr: str) -> bool:
    """Validasi output: minimal 2 kalimat, panjang wajar, dalam Inggris."""
    if not tldr or len(tldr.strip()) < 20:
        return False
    # Minimal ada 1 titik (2 kalimat)
    sentences = [s.strip() for s in tldr.split('.') if len(s.strip()) > 5]
    if len(sentences) < 1:
        return False
    # Cek tidak diawali kata bahasa Indonesia yang umum
    indo_starters = ["penelitian", "makalah", "studi", "sistem", "metode", "pengembangan"]
    first_word = tldr.strip().split()[0].lower()
    if first_word in indo_starters:
        return False
    return True


# ============================================================
# 4. CORE FUNCTION
# ============================================================

def generate_tldr(
    abstract: str,
    max_new_tokens: int = 100,
    repetition_penalty: float = 1.2,
    verbose: bool = False
) -> Optional[str]:
    """
    Generate ontology-aware 2-sentence TLDR dari abstract paper.
    
    Args:
        abstract: Abstract paper (bisa Indo, Inggris, atau campur)
        max_new_tokens: Batas token output (100 cukup untuk 2 kalimat)
        repetition_penalty: Hindari repetisi token
        verbose: Print debug info
    
    Returns:
        TLDR string dalam Inggris, atau None jika validasi gagal
    """
    if not abstract or len(abstract.strip()) < 10:
        logger.warning("Abstract terlalu pendek atau kosong.")
        return None

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": f"Abstract:\n{abstract.strip()}\n\nTLDR:"},
    ]

    # Tokenize dengan chat template
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    inputs = tokenizer(text, return_tensors="pt").to(model.device)

    if verbose:
        logger.info(f"Input token count: {inputs['input_ids'].shape[1]}")

    # Generate — greedy decoding untuk reproducibility di pipeline KG
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,            # Greedy: deterministik, cocok untuk pipeline
            repetition_penalty=repetition_penalty,
        )

    # Decode hanya bagian output baru (bukan prompt)
    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True
    ).strip()

    if verbose:
        logger.info(f"Raw output: {response}")

    # Validasi
    if not validate_tldr(response):
        logger.warning(f"Validasi gagal untuk output: '{response[:80]}...'")
        return None

    return response


# ============================================================
# 5. BATCH PROCESSING — Untuk Pipeline KG (Banyak Paper)
# ============================================================

def batch_generate_tldr(
    abstracts: list[dict],
    id_field: str = "paper_id",
    abstract_field: str = "abstract",
    verbose: bool = False
) -> list[dict]:
    """
    Proses banyak paper sekaligus. Input list of dict.
    
    Args:
        abstracts: List of dict, tiap dict minimal punya id_field dan abstract_field
        id_field: Nama key untuk ID paper
        abstract_field: Nama key untuk abstract
        verbose: Print progress
    
    Returns:
        List of dict dengan tambahan field 'tldr' dan 'tldr_status'
    """
    results = []
    total = len(abstracts)

    for i, paper in enumerate(abstracts):
        paper_id = paper.get(id_field, f"paper_{i}")
        abstract = paper.get(abstract_field, "")

        if verbose or i % 10 == 0:
            logger.info(f"Processing [{i+1}/{total}] paper_id: {paper_id}")

        tldr = generate_tldr(abstract, verbose=verbose)

        result = {
            **paper,  # Pertahankan semua field asli (title, author, dll.)
            "tldr": tldr,
            "tldr_status": "success" if tldr else "failed",
        }
        results.append(result)

    success_count = sum(1 for r in results if r["tldr_status"] == "success")
    logger.info(f"Batch selesai: {success_count}/{total} berhasil.")
    return results


# ============================================================
# 6. TESTING
# ============================================================

if __name__ == "__main__":

    # --- Test 1: Abstract Bahasa Indonesia ---
    print("\n" + "="*60)
    print("TEST 1: Abstract Bahasa Indonesia")
    print("="*60)

    abstract_indo = (
        "Perkembangan industri hiburan digital yang pesat menuntut adanya sistem yang dapat "
        "membantu pengguna menemukan konten yang relevan secara cepat dan akurat. "
        "Fokus utama pengembangan ini adalah mengatasi dua permasalahan utama dalam "
        "Collaborative Filtering, yaitu data sparsity dan cold start problem. "
        "Penelitian ini menggunakan pendekatan kuantitatif dengan metode eksperimen "
        "dan dilakukan evaluasi terhadap fungsionalitas performa dan akurasi sistem. "
        "Hasil uji pengguna menunjukkan bahwa sistem mudah digunakan, cepat dalam "
        "merespon, serta mampu memberikan rekomendasi yang relevan."
    )
    tldr_1 = generate_tldr(abstract_indo, verbose=True)
    print(f"Output:\n{tldr_1}\n")

    # --- Test 2: Abstract Bahasa Inggris ---
    print("="*60)
    print("TEST 2: Abstract Bahasa Inggris")
    print("="*60)

    abstract_english = (
        "We present a new approach for scientific document summarization using "
        "transformer-based models. Our method introduces title scaffolding as an "
        "auxiliary task to improve salience selection. Experiments on the SciTLDR "
        "dataset show ROUGE-1 improvements of 3.2 points over the BART baseline."
    )
    tldr_2 = generate_tldr(abstract_english, verbose=True)
    print(f"Output:\n{tldr_2}\n")

    # --- Test 3: Abstract Campur Indo-Inggris ---
    print("="*60)
    print("TEST 3: Abstract Campur Indo-Inggris")
    print("="*60)

    abstract_mixed = (
        "This paper proposes penggunaan Graph Neural Network untuk knowledge graph completion. "
        "Kami menggunakan dataset FB15k-237 dan WN18RR sebagai benchmark. "
        "Model yang diusulkan mencapai MRR 0.38 pada FB15k-237, "
        "melampaui baseline TransE dan RotatE."
    )
    tldr_3 = generate_tldr(abstract_mixed, verbose=True)
    print(f"Output:\n{tldr_3}\n")

    # --- Test 4: Batch Processing ---
    print("="*60)
    print("TEST 4: Batch Processing")
    print("="*60)

    sample_papers = [
        {
            "paper_id": "paper_001",
            "title": "Sistem Rekomendasi Berbasis Collaborative Filtering",
            "abstract": abstract_indo,
        },
        {
            "paper_id": "paper_002",
            "title": "Scientific Summarization with BART",
            "abstract": abstract_english,
        },
        {
            "paper_id": "paper_003",
            "title": "GNN for Knowledge Graph Completion",
            "abstract": abstract_mixed,
        },
    ]

    batch_results = batch_generate_tldr(
        sample_papers,
        id_field="paper_id",
        abstract_field="abstract",
        verbose=False
    )

    for res in batch_results:
        print(f"\n[{res['paper_id']}] {res['title']}")
        print(f"  Status : {res['tldr_status']}")
        print(f"  TLDR   : {res['tldr']}")

    # --- Simpan hasil ke JSON (siap untuk pipeline KG berikutnya) ---
    output_path = "tldr_results.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(batch_results, f, ensure_ascii=False, indent=2)
    print(f"\nHasil disimpan ke: {output_path}")

In [3]:
import time
import pandas as pd
from src.etl.transform.enricher import generate_local_tldr

# 3 Contoh abstrak dengan kepanjangan dan bahasa yang bervariasi
test_abstracts = [
    "Perkembangan industri hiburan digital yang pesat menuntut adanya sistem yang dapat membantu pengguna menemukan konten yang yang relevan secara cepat dan akurat. Fokus utama pengembangan ini adalah mengatasi dua permasalahan utama dalam Collaborative Filtering, yaitu data spartsity dan cold start problem. Penelitian ini menggunakan pendekatan kuantitaif dengan metode eksperimen dan dilakukan evaluasi terhadap fungsionalitas performa dan akurasi sistem. Selain itu hasil uji pengguna menunjukkan bahwa sistem mudah digunakan, cepat dalam merespon, serta mampu memberikan rekomendasi yang relevan.",
    
    "This study investigates the impact of deep learning architectures on natural language processing tasks. We propose a novel transformer-based model that utilizes sparse attention mechanisms to reduce computational complexity by 40% while maintaining state-of-the-art accuracy on the GLUE benchmark. The dataset comprises 10 million bilingual sentence pairs. Our evaluation demonstrates significant improvements in translation fluency and inference speed.",
    
    "Analisis sentimen pada ulasan e-commerce berbahasa Indonesia membutuhkan teknik pemrosesan yang cermat karena struktur bahasa yang tidak baku. Makalah ini mengkaji penerapan Support Vector Machine (SVM) dan Naive Bayes Classifier bertingkat. Pra-pemrosesan data dilakukan menggunakan teknik stemming sastrawi dan pembobotan TF-IDF. Eksperimen yang dilakukan pada 5000 ulasan produk dari berbagai marketplace menunjukkan bahwa SVM mengungguli algoritma lain dengan F1-score sebesar 89.5%, membuktikan efektivitas metode linear pada dataset teks berdimensi tinggi."
]

print("🚀 MEMULAI BENCHMARK KECAPATAN GENERASI TL;DR (PEFT SciTLDR)")
print("="*80)

total_time = 0
results = []

# Proses Pemanasan (Warm-up) Model
# Panggilan pertama biasanya lebih lama karena model sedang di-load ke RAM ke GPU
print("⏳ Melakukan pemanasan model (Warm-up)...")
_ = generate_local_tldr("Warmup", test_abstracts[0])

# Mulai iterasi perhitungan waktu asli
for i, abstract in enumerate(test_abstracts, 1):
    input_words = len(abstract.split())
    print(f"\n[Test {i}/3] Mengekstrak Abstrak ({input_words} kata)...")
    
    # Titik awal perhitungan
    start_time = time.time()
    
    tldr = generate_local_tldr(f"Test Paper {i}", abstract)
    
    # Titik akhir perhitungan
    end_time = time.time()
    
    elapsed = end_time - start_time
    total_time += elapsed
    out_words = len(tldr.split()) if tldr else 0
    
    print(f"⏱️ Waktu proses  : {elapsed:.2f} detik")
    print(f"📝 Hasil TL;DR   : {tldr}")
    
    results.append({
        "Skenario": f"Test {i}",
        "Kata Input": input_words,
        "Kata Output": out_words,
        "Waktu Eksekusi (Detik)": round(elapsed, 2)
    })

print("\n" + "="*80)
print(f"📊 KESIMPULAN BENCHMARK")
print(f"Total Waktu       : {total_time:.2f} detik")
print(f"Rata-rata per TLDR: {total_time/len(test_abstracts):.2f} detik")

# Menampilkan statistik dalam bentuk tabel
df_bench = pd.DataFrame(results)
display(df_bench)

🚀 MEMULAI BENCHMARK KECAPATAN GENERASI TL;DR (PEFT SciTLDR)
================================================================================
⏳ Melakukan pemanasan model (Warm-up)...

[Test 1/3] Mengekstrak Abstrak (77 kata)...
⏱️ Waktu proses  : 172.40 detik
📝 Hasil TL;DR   : This paper aims to address two main problems in collaborative filtering algorithms by utilizing a new approach based on K-means clustering with experiments carried out for evaluating their performance and effectiveness. The results show that this system can be easily used, fast in response time, and provides relevant recommendations.

[Test 2/3] Mengekstrak Abstrak (58 kata)...
⏱️ Waktu proses  : 68.71 detik
📝 Hasil TL;DR   : We proposed a new Transformer based NLP system with reduced computation cost for machine translations.

[Test 3/3] Mengekstrak Abstrak (70 kata)...
⏱️ Waktu proses  : 188.93 detik
📝 Hasil TL;DR   : This paper aims to analyze sentiment analysis for Indonesian e-commerce reviews with a focus on support vector machine (SVM). The study uses stemming techniques from Sastrawi and TF-IDF feature encoding methods. Extensive experiments show that SVD outperform other algorithms when evaluating the performance of text-based review datasets.

================================================================================
📊 KESIMPULAN BENCHMARK
Total Waktu       : 430.04 detik
Rata-rata per TLDR: 143.35 detik

  Skenario  Kata Input  Kata Output  Waktu Eksekusi (Detik)
0   Test 1          77           49                  172.40
1   Test 2          58           15                   68.71
2   Test 3          70           47                  188.93